### ISSUE TITLE
Feature Suggestion - Remove query string from referrer

### ISSUE THREAD

**Issue by mchlbowyer** [ibericode/koko-analytics#1]
Hi, I think this is a really great product. One suggestion would be to remove the query string from referrers, or show it separately. If you have a long query string then it completely messes up the display: 
<img width="637" alt="Screenshot 2019-11-03 at 20 01 47" src="https://user-images.githubusercontent.com/50271531/68090506-c8cc3b80-fe74-11e9-8e78-5c3dfbaf26c5.png">
I am thinking something similar to this (although this does compress referrers by changing the different locales of Google, Facebook etc to a single entry):
<img width="648" alt="Screenshot 2019-11-03 at 20 03 39" src="https://user-images.githubusercontent.com/50271531/68090527-1183f480-fe75-11e9-983b-3bde4f1b0757.png">

**Comment by dannyvankooten** [comment]
Hey @mchlbowyer,

So cool that you already came across this and even installed it! Did not really expect that, hah. Working on a v1 to publish to WordPress.org in the next few weeks.

I agree, that looks nasty and even exposes some stuff that probably should not be tracked. The issue with this is that some sites still use query strings for their routing and I don't really want to break that, although I think that it's still better to break _some_ URL's versus having a bunch of clutter for most... 

Perhaps a whitelist of parameters is the way to go, so we can at least not remove WordPress' own parameters in case pretty permalinks are not configured.
