### ISSUE TITLE
Feature suggestion: Event tracking

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#10]
Personally I feel event tracking, like keeping track of the number of people submitting a contact form, is one of the most important metrics for a lot of website where the main goal is to get people to reach out to the website owner.

Two possible ways of going about this:

- Automatically keep track of all form submissions and use the form ID or other information in the form element as a sort of label.
- Manually add event tracking to just the interactions a site owner needs: link clicks, form submissions, focusing on a form input, etc.

We could start out with just the manual approach and when that's working well enough, slowly shift to a more automated way. 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by TyWood** [comment]
Hi Danny, thank you for your wonderful work on Koko Analytics!

I am not sure if this is possible as I am no developer, but I would be truly grateful if you could have "internal link clicks tracking," in addition to "external link clicks tracking." 

This is because I would like to see how viewers are circulating around my website & what kind of external websites they are interested in enough to click links.

Matomo Analytics tracks external link clicks as "Outlinks," but it has few roundabout ways to track internal link clicks. This is the very reason I cannot get rid of Google Tag Manager.

I created my Github account in order to post this comment. Anyway, thank you again for handy and lightweight Koko Analytics!

**Comment by dannyvankooten** [comment]
Hey @TyWood,

Thanks for dropping by! Sorry I'm a bit late to respond but my partner and I have been expecting a baby (due 8 days ago, still waiting) so I haven't been able to work as much.

Tracking link clinks, whether internal or external, is something that would be covered by event tracking at the very least, which will definitely end up in the plugin soon-ish so that should be good to know. For example, you could add a tiny snippet of JavaScript to your website to track _all_ link clicks and categorise them by `Outlink: <link-name>` and `Inlink: <link-name>` so it's easy to distinguish both.

That said, if it's visitor flow you're interested in there might be simpler ways to go about this, although I would have to think a little more on what that would look like. Do you have a good example of how you would like this to work ideally?

**Comment by TyWood** [comment]
Thank you very much for your  detailed reply, @dannyvankooten ! I too am really sorry for my late response. I was not feeling well.

I am happy to hear that link clicks tracking is likely to be implemented, and differentiating external and internal link clicks will not be a problem. 

My ultimate ideal would be that Koko Analytics can display 

1. Which links got how many clicks , and the "Total" row
2. After clicking a figure in the "How many clicks" column, in which URL the links were clicked how many times, and the "Total" row

Here is what I tried plotting:

**1st Displayed**
[External link clicks]
Clicked URL	| Clicks
--- | ---
https://example.com/dogs | 50
https://example.net/seashore | 20
--- | ---
Total | 70

[Internal link clicks]
Clicked URL	| Clicks  
--- | ---
/ | 100
/about | 40
/privacy-policy | 30
--- | ---
Total | 170

**Displayed after clicking a figure in the "How many clicks" column, for example "30" of "/privacy-policy" **

Clicked where | Clicks 
--- | ---
/ | 25
/about  | 5
--- | ---
Total | 30

However, even only the 1st one will be a big plus to know how many and what kind of link clicks happened. 

I run my small mainly book review website as a pure hobby, so large-scale website owners and marketers might have different wishes.

Thank you for being open to users', even laypeople's comments!

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/event-pdf-downloads-tracking/

**Comment by SteelWagstaff** [comment]
Hey @dannyvankooten -- thanks for your work on privacy-respecting web analytics. Very much appreciate it. Love Koko and what it offers for WordPress site admins. 

We make open-source book publishing software built on the WordPress platform that allows people to [publish free copies of the book in various export formats to the book's homepage] (https://guide.pressbooks.com/chapter/distribution-exported-files/). We've added a single custom filter for Google Analytics which tracks book download events from a book's homepage (https://github.com/pressbooks/pressbooks-book/blob/77e3d130dca6cf24df8a1fb921017df5a4f38997/partials/content-cover-book-header.php#L73-L82)

We'd love to be able to use Koko for something similar -- if that was possible, then we we able to totally support our users who want to drop Google Analytics but still gather basic information about page views and file download events for the books they publish.

**Comment by arnelap** [comment]
Another request for event tracking, to track outbound links that moved people away from the site. 
https://wordpress.org/support/topic/could-you-please-add-those-features/

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/tracking-downloads-13/

**Comment by Rhoslyn92** [comment]
I'm very interested in this feature! I manage a website with many downloadable PDF resources. Ideally I'd like the be able to apply multiple categories/tags to files, and see download #s in various combinations. For example, being able to look at all downloads in a particular language, or all downloads for resources on a particular topic.

**Comment by wpgaurav** [comment]
Let's get done with events! It's been a long wait.

**Comment by dannyvankooten** [comment]
Hello everyone,

So at first I thought @wpgaurav was a tad rude as Koko Analytics is a free plugin and I'd rather not introduce such a complex feature and pay for it with my own time as I'm already investing quite a bit of money in Koko Analytics to provide free plugin support on the WordPress.org forums. But it did get me thinking about the future of the plugin...

So, I've decided to invest some more time into Koko Analytics and start offering event tracking and email reports as a paid add-on plugin. The [OpenCollective](https://opencollective.com/koko-analytics) initiative is simply not working, so hopefully this will allow some people to start contributing to the plugin in a meaningful way.

I'm currently looking for input on what you think event tracking should look like, but here's what I had in mind:

**Event Tracking**

You can call `koko_analytics.trackEvent( "event name", { custom: "params" })` from JavaScript to record any event name you like along with custom parameters.If you then add a widget to your dashboard for this event it shows how many times it was triggered grouped by its parameters.

For example, let's say you're firing `koko_analytics.trackEvent( 'click', { url: "/contact/" })` and `koko_analytics.trackEvent( 'click', { url: "/download/" })`..

You can then add a new dashboard widget to your Koko Analytics dashboard and specify `click` as the event name for that widget. It will then show you a list of click events with the `url` parameter as a column. Like this:

| URL        | Visitors | Events |
|------------|----------|--------|
| /contact/  | 1        | 5      |
| /download/ | 1        | 2      |

Thoughts?

**Comment by wpgaurav** [comment]
Hi @dannyvankooten , I wanted to show how desperately some of us want some extra features. 👍🏼  I am already paying for HTML forms, so I'll be more than happy to pay for this as well. Your format looks really nice. If events are too big a thing right now, maybe we could at least have a section like this: 
![Jetpack Stats ‹ Compass by Rau's IAS — WordPress com 2023-09-003108](https://github.com/ibericode/koko-analytics/assets/3599257/ce9f8ec7-1e7f-48a1-bd62-79c8848b0e05)
Source: Jetpack Stats

**Comment by dannyvankooten** [comment]
Happy to share that there has been a ton of progress on this.

![image](https://github.com/ibericode/koko-analytics/assets/885856/e35e563c-c18c-4079-94ff-b450f1d0f6ab)


- [Live demo](https://www.kokoanalytics.com/?go-to-demo=1), the bottom two blocks are powered by custom event tracking.
- Some early documentation on tracking events: [Tracking custom events with Koko Analytics](https://www.kokoanalytics.com/kb/tracking-events/)

The approach laid out above turns out to be pretty versatile. In its simple form we're currently using it to track outbound clicks.

More creatively we're also using it to power the "is this helpful?" question at the bottom of the knowledge base pages. If someone clicks "yes" we track a custom event with a positive value and we send a negative event value if someone chooses "no".

![image](https://github.com/ibericode/koko-analytics/assets/885856/0105fbf3-805d-4958-ab92-a466b8727a59)
![image](https://github.com/ibericode/koko-analytics/assets/885856/34604e48-f78c-4609-a3dc-f49c9386f211)

**Comment by dannyvankooten** [comment]
Event tracking is now possible with [Koko Analytics Pro](https://www.kokoanalytics.com/pricing/) :tada:

**Comment by wpgaurav** [comment]
Cheers @dannyvankooten :) Purchased Koko Analytics Pro. Slowly migrating to it from GA4. 

Maybe there is some option to reduce the cost for us in the third-world countries. 1 License of HTML Forms already costs $81 a year, and there are no renewal discounts. So, I can use these on just one blog and not on others at the moment. Please look at this as well. 🙌🏼

**Comment by dannyvankooten** [comment]
Nice @wpgaurav! And I'd love to offer such an option, do you have any examples of other paid plugins doing this in a way that you think is good?

**Comment by eduwass** [comment]
@dannyvankooten is event tracking not an option anymore?
