### ISSUE TITLE
Analytics AMP pages 

### ISSUE THREAD

**Issue by Mathijsvdbeek** [ibericode/koko-analytics#100]
Hi,
Nice plugin. I like it. The AMP pages of the plugin https://nl.wordpress.org/plugins/accelerated-mobile-pages/ is not being counted. Is there a way to solve this? Maybe add a piece of AMP code in the amp template page? Or maybe you have an other sulution?

Kind regards :)

**Comment by dannyvankooten** [comment]
Hello @Mathijsvdbeek,

Koko Analytics only supports the [official AMP plugin for WordPress](https://wordpress.org/plugins/amp/) right now, so if you switch to that then things will work right away. Is there a reason you're using this plugin vs. the official one?

Am open to pull requests adding support for this plugin, but probably won't be spending any time on it myself as it's a commercial product.

**Comment by Mathijsvdbeek** [comment]
Is there a reason you're using this plugin vs. the official one? 

It was working better in the beginning (no google problems). This plugin supports list of childpages. Later on I changed the templates so the AMP page looks exactly as I want. Also it supports blog overview or tag overview. Maybe this is now also possible with the official plugin. I will have a look again.
