### ISSUE TITLE
Feature suggestion: setting to enable/disable the stats for specific roles within WordPress

### ISSUE THREAD

**Issue by jeroenrotty** [ibericode/koko-analytics#102]
In most websites I launch for customers, I give them a editor role or custom role. It would be very cool if Koko has a setting where I can enable/disable it for any role.

**Comment by jeroenrotty** [comment]
@dannyvankooten Any news or do you have a snippet around where to hook in? Was quickly looking around but seems I can't find correct hooks/code to make the widget show for Woo shop managers. It would be great if admins can decide for which roles the widget is shown/hided.


// SHOW KOKO WOO SHOP MANAGER

add_action( 'admin_init', function() {
	// only run on koko analytics page
	if ( ! isset( $_GET['page'] ) || $_GET['page'] !== 'koko-analytics' ) {
		return;
	}

	// add "view_koko_analytics" capability to "shop manager" role
	$role = get_role( '**shop_manager**' );
	$role->add_cap( 'view_koko_analytics' );
});

**Comment by jeroenrotty** [comment]
Thought the snippet would work found in the code snippets folder:

```
<?php

add_action( 'admin_init', function() {
	// only run on koko analytics page
	if ( ! isset( $_GET['page'] ) || $_GET['page'] !== 'koko-analytics' ) {
		return;
	}

	// add "view_koko_analytics" capability to "editor" role
	$role = get_role( 'shop_manager' );
	$role->add_cap( 'view_koko_analytics' );
});
```
But guess I'm missing a thing :D

**Comment by dannyvankooten** [comment]
Hey @jeroenrotty,

The easiest way to go about this is by using the [User Role Manager](https://wordpress.org/plugins/user-role-editor/) plugin. You can use it to add either the `manage_koko_analytics` or `view_koko_analytics` (or both) capability to any of your user roles. You can remove the User Role Editor plugin after adding the capability.

You could also use a snippet like the one you pasted, but since capabilities are stored in the database you probably only want to run it once. 

I hope that helps. If not, let me know please!

**Comment by jeroenrotty** [comment]
That worked very easily, great. Thanks for the intel!

**Comment by dannyvankooten** [comment]
Happy to hear it @jeroenrotty. Will look at adding this to the FAQ so it's more easily available. 😃

**Comment by jeroenrotty** [comment]
Great. One more thing, where do I donate? Are you open for that?

**Comment by dannyvankooten** [comment]
@jeroenrotty No need (thank you though!), but if you really insist then I'm a big fan of [effective giving](https://www.givewell.org/charities/top-charities) and a donation to one of their listed top charities would be amazing.

If you want something more specific to Koko then writing a (can be super short) post on your website about Koko or listing it as a used software package is about the best thing you can do to make me super happy. 💘

**Comment by jeroenrotty** [comment]
Hi @dannyvankooten,

I'll donate to one of those charities per your suggestion. 👍 

For the latter, I already wrote on wpinfo.be about Koko =). See: https://wpinfo.be/site-statistieken-zonder-de-privacy-van-je-bezoekers-te-schenden/
