### ISSUE TITLE
Feature: Show total visits to a post/page in frontend admin bar

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#108]
Show statistics per post, in the admin bar and in the backend. 
Like a bar chart with visits per day for that specific post.

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/how-to-see-stats-of-a-single-url/#post-15632985

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/any-questions-6/

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/widget-visitors/ sort of

**Comment by dannyvankooten** [comment]
Closing this to keep GitHub issue list about issues and bugs only, but tracking this feature request is continued here: #211

**Comment by dannyvankooten** [comment]
PS. Showing the number of pageviews and visitors over time for a specific post or page in the regular Koko Analytics dashboard is a feature of the free plugin.

![Image](https://github.com/user-attachments/assets/3dee3540-03c3-45f3-8ca5-9381d4dd5961)
