### ISSUE TITLE
Feature: Count request variables as separate pages

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#109]
https://wordpress.org/support/topic/support-for-registered-query-vars/

> i work with one page to display several data based on url parameters. in your page statistics there is that one page only which is bad. i need more details. which parameter was used? i register them via query_vars hook and then i use them like:
> url.com/my_page/?view_mode=list
> url.com/my_page/?theme=stars
> url.com/my_page/?sort_order=asc

https://wordpress.org/support/topic/support-for-registered-query-vars/

**Comment by dannyvankooten** [comment]
Given the current way Koko tracks pageviews, this will be very hard to accomplish as Koko Analytics is post-object based, not URL string based. Therefore I'm closing this as I don't see this happening in the near future, sorry.
