### ISSUE TITLE
Feature suggestion: Count browser type statistic

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#11]
For each new site visitors, keep track of their browser type and perhaps major version number.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by Zodiac1978** [comment]
Tracking browsers could be much harder in the future:
https://www.zdnet.com/article/vivaldi-to-change-user-agent-string-to-chrome-due-to-unfair-blocking/

**Comment by marcelismus** [comment]
+1

**Comment by dannyvankooten** [comment]
Moved to #222
