### ISSUE TITLE
Feature: Show posts / pages with 0 visits

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#110]
As requested here: https://wordpress.org/support/topic/pages-displays-only-from-1-not-0/

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by msaari** [comment]
I've created [Extra Analytics for Koko](https://github.com/msaari/extra-analytics-for-koko) plugin, which shows more information from the Koko stats. I just added "zero views" feature to the plugin.

**Comment by dannyvankooten** [comment]
@msaari That definitely sounds interesting! Do you have a screenshot of your plugin's functionality?

**Comment by msaari** [comment]
I added some here: https://github.com/msaari/extra-analytics-for-koko/wiki/Extra-Analytics-Screenshots.

It's very basic at the moment.
