### ISSUE TITLE
Enhancement / Bug: Scaling of the chart

### ISSUE THREAD

**Issue by danielrunvegan** [ibericode/koko-analytics#112]
A few days ago our site exceeded 20.000 daily page views for the first time, leading to a change of the scale of the analytics chart. However, the scale went from a maximum of 20k straight to a maximum of 60k, which unnecessarily compresses the chart (see screenshots below).

My suggestion would be to have a smaller scale jump - maybe always to the next 10k when the pageviews are in the double-digit k's.

![koko-1](https://user-images.githubusercontent.com/60192889/106724102-1e5b3f00-6608-11eb-8736-816fb93d7ccf.jpg)
![koko-2](https://user-images.githubusercontent.com/60192889/106724109-1ef3d580-6608-11eb-9a93-290835cbd662.jpg)

**Comment by dannyvankooten** [comment]
Hah, nice. The algorithm that is used for determining the labels on the y-axes should definitely be improved for this particular range... I'll have a stab at it!
