### ISSUE TITLE
Allow to add custom date presets

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#113]
Maybe by including a non-updated file like date-presets-custom.js or such?

https://wordpress.org/support/topic/another-suggestion-4/#post-14023645

**Comment by dannyvankooten** [comment]
The need for this should be alleviated after fe603a5169391fc43127577c43c428dcd9c4fdcc, which includes both a) more date presets and b) two input fields for setting a custom date from keyboard input
