### ISSUE TITLE
Bug: Date picker not working after update to 1.0.25

### ISSUE THREAD

**Issue by danielrunvegan** [ibericode/koko-analytics#114]
After the latest update I see additional date presets in the "date picker" dropdown menu. However, after clicking any of the presets the chart remains unchanged. It only shows the selected preset when I choose it as a default on the settings page, save and return to the analytics page.

As a side note, I am really sad to see that the "last 28 days" preset has been removed ... I think this kind of "floating" view makes great sense, and is a standard for most web analytics applications (I think Google Analytics has "last 7 days" and "last 30 days").

**Comment by dannyvankooten** [comment]
Hey Daniel,

Thank you for the bug report! What browser are you using?

**Comment by danielrunvegan** [comment]
I'm using Chrome. Just checked with several other browsers and it only works in Firefox for me (Opera and Edge don't work either).
