### ISSUE TITLE
Feature: Shortcodes to show statistics to visitors

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#115]
eg [koko] for showing the total views of that page.

 You could even consider adding a "totals per page" record in the database that is not purged and will increase loading speeds for pages with such a shortcode.

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/switch-from-wp-statistics-to-koko/

**Comment by AnilRedshift** [comment]
Hey @arnelap, here's a basic working example for the whole website. I'll add support for per-post as well:
https://github.com/ibericode/koko-analytics/pull/120

**Comment by dannyvankooten** [comment]
Not showing the total views of that page, but still kind of related is the `[koko_analytics_most_viewed_posts]` shortcode which renders a list of the most viewed posts in the last 30 days by default.

Example use:

```
[koko_analytics_most_viewed_posts days=30 number=10]
```

**Comment by dannyvankooten** [comment]
Kind of related to #206
