### ISSUE TITLE
Translate calendar date picker

### ISSUE THREAD

**Issue by timiwahalahti** [ibericode/koko-analytics#116]
Currently, the calendar date picker is not translatable nor translated into the user's language. It would be good to have months, days and day abbreviations translated. Also setting the date format could be useful.

**Comment by dannyvankooten** [comment]
Somehow WordPress.org is no longer picking up on the translatable strings... Not sure why (yet).

**Comment by dannyvankooten** [comment]
I think WordPress.org picks up on the strings again now, after pushing the development (source) files to WordPress.org too. I don't think GlotPress can parse the strings from the minified JavaScript files as function names are mangled to preserve characters... 

Not sure if installations will now automatically pick up on the new translations or that a new version release is necessary. I guess we'll know after a day or two.
