### ISSUE TITLE
Optimize date picker for mobile view

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#117]
https://wordpress.org/support/topic/mobile-optimization-18/#post-14094911

![image](https://user-images.githubusercontent.com/9718808/109001995-36d6ea80-76d8-11eb-91f5-f75582f8a588.png)
![image](https://user-images.githubusercontent.com/9718808/109002027-3f2f2580-76d8-11eb-84ef-06698d3ee3d5.png)
![image](https://user-images.githubusercontent.com/9718808/109002044-448c7000-76d8-11eb-83b7-6d548058cd56.png)

**Comment by binaryfire** [comment]
Can confirm I'm having these issues too
