### ISSUE TITLE
Feature: UTM parameters

### ISSUE THREAD

**Issue by davleone** [ibericode/koko-analytics#118]
Could it be possible to integrate UTM parameters in Koko Analytics statistics? 

Right now I cannot figure out what social media or specific campaign is working for my (non-commercial) blog. At least in my case, referrer has very few data and is not that useful. 

Imho it will be good both for non-commercial and commercial websites, as this way it would be possible to understand where resources (time, attention, and often money) are used effectively. 

Pros: 
- It will be possible to determine how effective social and ads campaign are
- UTM parameters are a common standard 
- Non-invasive tracking

Cons: 
- Koko will became more complicated (possible solution: only include _utm_source_ and _utm_campaign_)
- Performance slowdown (possible solution: checkbox to disable this function)

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/how-to-track-campaigns/#post-15069197

**Comment by sushinger** [comment]
Any news about this feature request?

**Comment by dannyvankooten** [comment]
No news yet, although I do like this feature. 

At the very least this will be partially supported by our [custom event tracking feature](https://www.kokoanalytics.com/kb/tracking-events/), which is currently in closed beta and will be available in Koko Analytics Pro very soon.

**Comment by dannyvankooten** [comment]
Continuing tracking of this feature suggestion in #209
