### ISSUE TITLE
Feature suggestion: Remove visitors when cookies are disabled

### ISSUE THREAD

**Issue by davleone** [ibericode/koko-analytics#121]
At least in my experience, when cookies are disabled "visitors" and "views" overlap. They usually have less than 1% difference; every 1000 views, there are at least 990 visitors, but usually 995 or more. 

Therefore, visitors stats becomes kinda useless as there is no significant difference. With cookies enabled there is a significant difference between these two data. 

Would it be possible to disable them overall when cookies are not used? 

Pros: 
- Simplified UI
- Significantly smaller database: for any given day there would be only one data (views) instead of two (views and visitors)
- Better performance (less data collected and processed) 

Cons: 
- Might be tricky to implement

**Comment by dannyvankooten** [comment]
Continuing the discussion in #208.
