### ISSUE TITLE
WP Consent API

### ISSUE THREAD

**Issue by GDvW** [ibericode/koko-analytics#124]
Could you declare to follow the guidelines of the WP consent API? On [this](https://wordpress.org/plugins/wp-consent-api/#description) page you can find how to do that.

Kind regards,
Gerrald

**Comment by dannyvankooten** [comment]
Hey,

Not entirely sure what the plugin does or what problem it solve, but would be happy to accept either a code snippet or a pull request.

**Comment by 7c00io** [comment]
I think this is pretty much the same request as #134.
