### ISSUE TITLE
Bug: Javascript error when loading site page with excluded user role

### ISSUE THREAD

**Issue by Evaldash** [ibericode/koko-analytics#125]
When viewing the site's page while logged in in WP (I selected my role to be excluded from stats), using the browser inspector while having cookie with consent configured, there is a javascript error:

Uncaught TypeError: window.koko_analytics is undefined

While yes, I do understand that it's because the required script isn't loaded (I looked at the plugin's code to find this out, confused me for a good hour), it would be nice if a dummy script were loaded or something, so no error would be present.

**Comment by Evaldash** [comment]
I figured it out, I'm an idiot. If anyone else is having this issue, disable the analytics (which you should disable anyway) cookies in your cookie settings within your site, then the script window.koko_analytics.use_cookie = true; won't be loaded...

**Comment by baden03** [comment]
How is this issue closed? When logged on as a user that does not have access to see the analytics widget the same JS error is being thrown. the JS should not even be loading if the user does not have access to view the widget.
`render(<Chart startDate={startDate} endDate={endDate} height={200} width={el.clientWidth} />, el)`
