### ISSUE TITLE
Feature: Total Views and Hits per Category / Taxonomy

### ISSUE THREAD

**Issue by larsschafer** [ibericode/koko-analytics#126]
requested here https://wordpress.org/support/topic/post-type-and-taxonomy-stats/

**Comment by arnelap** [comment]
and here https://github.com/ibericode/koko-analytics/issues/126

**Comment by arnelap** [comment]
duplicate of https://github.com/ibericode/koko-analytics/issues/62 , can be closed

**Comment by larsschafer** [comment]
Wrong email address?

**Comment by dannyvankooten** [comment]
I'm just closing this issue to keep the GitHub issue list about issues and bugs only. We're still tracking this feature suggestion here: #212
