### ISSUE TITLE
Individual Profile Page Views - Developing Idea

### ISSUE THREAD

**Issue by legendarywd** [ibericode/koko-analytics#131]
Hi Danny (and team?), a brilliant plugin that I am interested in using on a subscription based site, whereby clients advert their services and the public view/contact them based on that.
They would like an email once a month to say - 'profile views last 28days are: x, this is up x% on last month' for example.
I see part of this was answered/explained in #64 - any ideas how this can be extended as I see in the ending notes your realtime endpoint only extends to the last 24 hours.

**Comment by dannyvankooten** [comment]
Hey @legendarywd,

I'm sorry for the terribly late reply, but this is easy to build by querying the database table backing Koko Analytics directly. It's definitely outside the scope of the plugin itself though. 

We would like email summaries (#17) at some point, but globally (for the entire site), not for individual pages and definitely not linked to a user account on the website.

So I won't be spending any time on this myself, but know that the database structure itself is stable and can be used for such a thing.
