### ISSUE TITLE
Question: rationale of buffer file

### ISSUE THREAD

**Issue by 7c00io** [ibericode/koko-analytics#135]
Storing the log of visits in a file and then moving them into the database seems to be a somewhat backwards way of creating the aggregate statistics.

Is there a specific reason why we can't/wouldn't store the visits in the database; or even update the aggregate rows right away?

**Comment by dannyvankooten** [comment]
Yes, performance.

**Comment by 7c00io** [comment]
Thanks for answering this right away!

Did you find, the performance to be degraded by updating the aggregate rows, or just storing the "buffer" in the database would have a detrimental effect too?
