### ISSUE TITLE
Suggestion: Frontend Analytics

### ISSUE THREAD

**Issue by scysys** [ibericode/koko-analytics#140]
Same like this example for google analytics: https://wordpress.org/plugins/frontend-analytics/ 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by rghedin** [comment]
I practice transparency as much as possible in my site. Having analytics in front-end, public available, would be awesome. Maybe as a shortcode?

**Comment by dannyvankooten** [comment]
@rghedin I like the idea and hope to tackle it one day! In the meantime, why not re-use the dashboard in the backend itself? I implemented such a thing on [kokoanalytics.com](https://www.kokoanalytics.com/?go-to-demo) by creating a new user role with only the `view_koko_analytics` capability.

**Comment by dannyvankooten** [comment]
To add to my previous comment, here is a sample plugin which creates a new user with role `viewer` and listens to all URL's with `?go-to-demo=1` in them, which automatically logs in this `viewer` user and redirects it to the Koko Analytics dashboard.

```php
<?php
/*
Plugin Name:  Koko Analytics - Open Dashboard (demo)
Description:  Adds a "viewer" user role that can view koko analytics
Version:      1.0.0
Author:       Danny van Kooten
Author URI:   https://dannyvankooten.com
License:      MIT License
*/

register_activation_hook(__FILE__, function() {
	add_role('viewer', 'Viewer', [
		'view_koko_analytics' => true,
		'read' => false,
	]);

	$user =  get_user_by('login', 'viewer');
	if ( !$user) {
		$id = wp_create_user('viewer', '!x9127367xasd7127!S');
		$user = get_userdata($id);
	}

	$user->add_role('viewer');
	$user->add_cap('view_koko_analytics');
});

function ka_login_and_go_to_dashboard() {
	if (! is_user_logged_in()) {
		wp_signon([
			'user_login' => 'viewer',
			'user_password' => '!x9127367xasd7127!S',
		]);
	}

	wp_redirect(admin_url('/index.php?page=koko-analytics'));
	exit;
}

add_action( 'init', function() {
	if (isset($_GET['go-to-demo']) ) {
		ka_login_and_go_to_dashboard();
	}

	global $pagenow;
	if ($pagenow === 'index.php' && isset($_GET['page']) && $_GET['page'] === 'koko-analytics' && false === is_user_logged_in()) {
		ka_login_and_go_to_dashboard();
	}
});

add_action('admin_init', function() {
	global $pagenow;
	if ($pagenow === 'profile.php' || $_SERVER['REQUEST_METHOD'] !== 'GET') {
		wp_redirect(admin_url('/index.php?page=koko-analytics'));
		exit;
	}
});

add_action('admin_head', function() {
	echo '<style>#menu-users, #footer-upgrade, .update-nag, #screen-meta-links { display: none !important; }</style>';
});
```

**Comment by dannyvankooten** [comment]
Hello everyone. I'm just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.

FWIW, I've just rewritten the dashboard to not depend on anything that is usually available in WordPress admin, so this becomes a lot more feasible now.
