### ISSUE TITLE
Feature suggestion: Track search terms

### ISSUE THREAD

**Issue by gitatmax** [ibericode/koko-analytics#148]
---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by msaari** [comment]
It would be nice, but it's really hard to do; Google, for example, isn't keen on sharing the search terms used.

**Comment by gitatmax** [comment]
Sorry, I should have elaborated. I think what I’m asking isn’t to do with Google, but search terms on the site’s WP search.

**Comment by msaari** [comment]
Maybe Koko will add that. Meanwhile, my plugin [Relevanssi](https://wordpress.org/plugins/relevanssi/) improves the search and features internal search term tracking. The [Premium version also has click tracking](https://www.relevanssi.com/knowledge-base/click-tracking/) that shows you which posts users click from the search results.

**Comment by gitatmax** [comment]
@msaari Ah, how cool—I (clearly) had no idea you were behind Relevanssi! I've used that before; I will check it out again. Thanks for the suggestion.

**Comment by dannyvankooten** [comment]
Hello everyone. I'm just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.
