### ISSUE TITLE
Feature suggestion: Count 404 errors (page not found)

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#15]
Like we keep track of post, page and post type views, we could also keep track of pages that return a 404 page not found error. This can be helpful in discovering dead links.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by askel45** [comment]
Agreed! It is one of the things I look at monthly (or weekly) in my GA stats.

**Comment by dannyvankooten** [comment]
Moved to #218
