### ISSUE TITLE
Feature: Top posts shortcode

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#151]
Since the plugin already collects the most visited (popular) posts how about the ability to display the most popular posts with a shortcode? Make it easy to show most popular posts in widget/sidebar or in pages/posts. 

as requested: https://wordpress.org/support/topic/suggestion-shortcode-to-display-most-popular-posts/

**Comment by rghedin** [comment]
Not exactly what you're asking, but there is a widget that does exactly that, @arnelap. You can choose which post type to list, how many of them, how many days to use statistics for, and if you want to display post dates or not.

I can't tell you how to use this widget with blocks metaphor, nonetheless as a shortcode. I use a plugin ([Classic Widgets](https://wordpress.org/plugins/classic-widgets/)) to keep them as they were in WordPress 4.9 and it works like a charm.

**Comment by Rale379** [comment]
I also use classic widgets and classic sidebars with an [FSE theme](https://pcm.wordpress.org/themes/block-builder/). So, I'd also prefer a regular widget over a shortcode. But, either would be much appreciated.

A great feature would be the ability to write your own HTML, like in these widget plugins:
[WordPress Popular Posts](https://wordpress.org/plugins/wordpress-popular-posts/)
[Top 10 – Popular posts plugin for WordPress](https://wordpress.org/plugins/top-10/)
[AJAX Hits Counter + Popular Posts Widget](https://wordpress.org/plugins/ajax-hits-counter/)

All of these plugins need Ajax to function.
So, using Koko Analytics to get the data would be a much better solution.

It does not need to be very elaborate. We just need the ability to set the time frame, number of posts and maybe the category.

**Comment by dannyvankooten** [comment]
@arnelap This is already possible through the built-in widget, indeed.

There is also a shortcode that works like this:

``` 
[koko_analytics_most_viewed_posts]
```

Or with arguments:

```
[koko_analytics_most_viewed_posts number=10 post_type='post' show_date=0 days=30]
``` 

Alternatively, if one needs more control over the output HTML, there is also a PHP function to call:

```php 
$posts = KokoAnalytics\\get_most_viewed_posts( [ 'number' => 10, 'post_type => 'post', 'show_date' => false, days => 30 ]);
```

**Comment by Rale379** [comment]
@dannyvankooten

Thank you!
The shortcode works great.

I do need more control over the HTML and to add other elements to the layout.
But, I'm not good at PHP.
Could you please help me out a bit...?

Just show me how to add a thumbnail or excerpt.

I have a template for the layout in a PHP file, which I use for latest posts, related posts and in the main archive grid.
This is my latest posts shortcode:

```
add_shortcode( 'az_latest_posts','latest_posts_595151');
function latest_posts_595151(){

  query_posts( array ( 'posts_per_page' => 3 ) );
    if ( have_posts() ) : while ( have_posts() ) : the_post(); 
      include WP_CONTENT_DIR . '/custom-assets/php/blog-card-img-top.php';
        endwhile; 
      wp_reset_postdata();
    endif; 
  wp_reset_query();
}
```
