### ISSUE TITLE
Feature Suggestion: Add Pageviews to Posts & Pages Table

### ISSUE THREAD

**Issue by ckluis** [ibericode/koko-analytics#152]
I know some plugins make it available to add columns to the default tables for posts/pages.  I think it would be nice to layer this information into the primary posts/pages admin.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by kennydude** [comment]
It would be also great if this could be exposed as an api function for "get pageviews for these post ids"

**Comment by frietboer** [comment]
or even by wp_query

**Comment by dannyvankooten** [comment]
Hello everyone. I'm just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.

**Comment by dannyvankooten** [comment]
![image](https://github.com/user-attachments/assets/ba083dbc-0881-4608-a5e8-c70360312453)

![image](https://github.com/user-attachments/assets/6fec94ad-482f-482f-9b2a-ceeb96d823e1)

This has been added to [Koko Analytics Pro](https://www.kokoanalytics.com/pricing/).
