### ISSUE TITLE
Feature Suggestion: Display Both Onsite and Offsite Search Keywords on Stats Page

### ISSUE THREAD

**Issue by bhadaway** [ibericode/koko-analytics#153]
**Onsite** — Searches done through the WordPress search form. If considered, you can find an easy reference here: https://github.com/cornelRaiu/search-analytics.

**Offsite** — Utilizing Google Search Console to gather keywords. I realize that this was already suggested and closed 3 years ago (https://github.com/ibericode/koko-analytics/issues/32), but I wonder if the situation has changed any with the API: https://developers.google.com/webmaster-tools/.

For anyone thinking "Doesn't it defeat the purpose of improved privacy to bring Google back into the fold?" No, I think this is different. Google is still absolutely vital to sending traffic to our websites; that hasn't changed. The key feature of not sending user data to Google is still upheld. Rather, this would be for the purpose of Google sending data (that they've already collected regardless of anything we're doing) to us to give us insight into how people are searching and finding our sites.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Moved to #205
