### ISSUE TITLE
Feature Suggestion: Please Start Accepting Donations

### ISSUE THREAD

**Issue by bhadaway** [ibericode/koko-analytics#154]
@dannyvankooten — I think you've done a brilliant job with this plugin. I researched Google Analytics alternatives for months, came across dozens of options (including all the most popular ones like: Plausible, Matomo, Umami, etc.), and your solution was in the Goldilocks zone. It seems that the downside to moving away from Google Analytics is the need to pay money, register an account, or try to install some unnecessarily-complicated setup with half-ass instructions in order to self-host.

I literally searched for all the analytics plugins on WordPress and eliminated every single one that seemed to have some kind of catch or hoop to jump through, narrowing it down until only Koko remained.

You nailed it.

My nightmare search for a Google Analytics replacement is finally over, but I hope it stays that way.

Please add a PayPal or https://opencollective.com/ link on https://wordpress.org/plugins/koko-analytics/ and https://github.com/ibericode/koko-analytics.

Thank you!

**Comment by dannyvankooten** [comment]
Hello @bhadaway,

Thank you for the kind words. I think of Koko Analytics as my donation to the internet/society/you instead of hoping on some sort of financial return on it, but will look at adding a few options to chip in a few dollars. Have not really looked into any of the options yet though so would require some research, eg. have not heard of OpenCollective before. But will do some reading over the next few weeks!

**Comment by bhadaway** [comment]
I feel the same way about most of my own free projects. I think it's just fun to help out and I don't expect anything in return. Also, I felt icky for years about donations and refused to ever ask for them.

One day, I finally realized though that in the same way I contribute code, others who don't have those specific skills still want to contribute to the project in whatever way they can, either with ideas or money.

We have seen people be sleazy with how they ask for donations before, so it's not as though it's unprecedented. However, you don't even need to ever ask anyone to donate. Putting up a donate link is like putting out a tip jar; it's there for people who want to use it and doesn't stress out anyone who can't.

PayPal/Stripe/Open Collective are some of the more obvious options. If ever you come against a milestone you'd like to reach with a project, but can't because of limited funds, I really like https://donorbox.org/. It's super flexible in allowing people to donate in all kinds of ways and my favorite feature is that it gives you access to a meter widget that shows progress toward the goal that can be embedded anywhere.

Anyway, thanks again.
