### ISSUE TITLE
Plugin not showing up on wordpress

### ISSUE THREAD

**Issue by mmaaiinnee** [ibericode/koko-analytics#156]
The Koko Analytics plugin is showing up but not the content. One downloaded it’s just a plank backend page.

**Comment by dannyvankooten** [comment]
Hello,

Koko Analytics was recently added to the EasyPrivacy list which means it is now blocked by default in a lot of ad-blockers (like uBlock Origin). The filter rule blocks any JavaScript request with "koko-analytics" in the URL, meaning both the tracking script is blocked as is the script for viewing the dashboard page.

Whitelisting your domain in your ad-blocker settings should fix the problem.
