### ISSUE TITLE
Feature Suggestion: Show direct traffic

### ISSUE THREAD

**Issue by bergjs** [ibericode/koko-analytics#157]
As far as I can see only referrers are listed, but it would be great to know how many users came directly to the page via its URL.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by giuliopons** [comment]
I'm agree

**Comment by dannyvankooten** [comment]
Hello everyone. I'm just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.
