### ISSUE TITLE
Add a filter hook for URL normalization

### ISSUE THREAD

**Issue by msaari** [ibericode/koko-analytics#158]
I would like to normalize search engine URLs differently; I'd like to see how much Google traffic comes from the Finnish TLD, but I'd like to normalize everything else into one entry. I can see why you wouldn't want to do that by default. Could you please add a filter hook on the URL normalization?

```
public function normalize_url( $url ) {
	$aggregations = apply_filters(
		'koko_analytics_url_aggregations',
		array(
			'/(google|bing)\.([a-z]{2,3}(?:\.[a-z]{2,3})?)\/(?:search|url)/' => '$1.$2',
			'/(?:i|m)\.facebook\.com/' => 'facebook.com',
			'/linkedin\.com\/feed.*/' => 'linkedin.com',
			'/(?:www|m)\.baidu\.com.*/' => 'www.baidu.com',
			'/yandex\.ru\/clck.*/' => 'yandex.ru',
		)
	);

	return preg_replace( array_keys( $aggregations ), array_values( $aggregations ), $url, 1 );
}
```

This would be very helpful.

**Comment by dannyvankooten** [comment]
Done, @msaari! But not yet released.

Was wondering whether we should allow filtering on the entire aggregations array of just call a filter on a single URL instead:

```php
$normalized_url = apply_filters( 'koko_analytics_normalize_url', $url );
```

But went with the former (and also your suggested) approach as I think it should allow for more... Let me know what you think though.

**Comment by msaari** [comment]
I guess approaches are fine, but setting all the aggregations at once feels more effective =D

**Comment by dannyvankooten** [comment]
﻿
﻿
﻿
﻿
﻿
﻿
﻿
﻿
﻿
Guess you’re right! It also forces the end user into this more optimized approach vs. having them possibly maintain a giant switch statement or myriad of conditionals that could grow unwieldly really soon. Thanks for chiming in!

**Comment by msaari** [comment]
Sure, happy to help! Koko has been a nice tool, and I like how having access to the stats provides interesting opportunities, like this [Relevanssi integration](https://www.relevanssi.com/knowledge-base/integrating-koko-analytics-stats/) I did.
