### ISSUE TITLE
Plugin version: 1.0.33 -- Cron issue with no other information

### ISSUE THREAD

**Issue by kreezxil** [ibericode/koko-analytics#160]
The plugin is reporting that there is an issue with my sties wp-cron, but it doesn't say what it is that the problem is. I have access to the files that need to be fixed, etc. If i knew what the real deal is I could do something about it.

This appears at the top of the analytics page.

```
There seems to be an issue with your site's WP Cron configuration that prevents Koko Analytics from automatically processing your statistics. If you're not sure what this is about, please ask your webhost to look into this.
```

**Comment by dannyvankooten** [comment]
Hello @kreezxil,

The plugin shows this message if the `koko_analytics_aggregate_stats` event did not fire in the last hour, where it should normally run every minute. This may mean that either your entire WP Cron event system is not being fired or that some other event is blocking the task loop. 

It's impossible for Koko Analytics to tell which is which, it only sees that `koko_analytics_aggregate_stats` is not being fired and then rescheduled.

I would first check whether you are using the default WP Cron system or a "real" server-side cronjob and if so, whether that is configured correctly. There are various WP Cron related plugins that may help you dig into the issue.

**Comment by kreezxil** [comment]
thank you. :)

**Comment by dannyvankooten** [comment]
@kreezxil Did you manage to find the issue? Just curious, what was it? Am wondering how we can improve the message that Koko Analytics is showing. :slightly_smiling_face:

**Comment by kreezxil** [comment]
Nope, I thought it was some plugins doing it, but alas it's not. More
investigation.

**Comment by kreezxil** [comment]
Found it, my hosting provider that says I have unlimited space apparently
told a lie, as I have run out of space. My guess is someone on the node has
abused the system.

**Comment by kreezxil** [comment]
spoke too soon, that issue was resolved already. Looking thru my error_log,
I'm disabling the wp-cron and setting it to fire by system cron now. seeing
if that helps.

**Comment by kreezxil** [comment]
I see that your code checks the timestamps to see if it has been run not
more than every ten minutes. Is that in the description of the plugin
anywhere? Moreover, know that's what it is checking would make for a better
error to print to admin. Like something such as,

your site is reporting that the last time this plugin was run happened on
TIMESTAMP and that the next run time will be at TIMESTAMP_NEXT. It is
recommended that this Koko Analytics shouldn't run less than once every 10
minutes, and certainly not more than that.

Having such information would make it easier to nail down issues. :)

Thanks for having that info it has, anyway, It has helped a lot.
