### ISSUE TITLE
Track iframes

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#162]
Currently the trackPageview() functions has

 // do not track if page is inside an iframe
    if (window.location !== window.parent.location) {
      return
    }
Why?
Should we make this a setting?
In some cases people use lightbox to open posts and those should likely still be tracked.
Source: https://wordpress.org/support/topic/doesnt-count-content-loaded-in-iframes/#post-15985102

**Comment by dannyvankooten** [comment]
Don't have any strong feelings about this, but I think we can indeed reverse the default maybe.

**Comment by dannyvankooten** [comment]
closed via 2bfe3b9b090fcc597fa2e1da2b3a3f1b691fc733
