### ISSUE TITLE
Exclude pageviews from these user roles” box is blank when activating Koko on 1 site in a multisite setup

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#163]
Activating Koko Analytics plugin only in one subsite, I also noticed that “Exclude pageviews from these user roles” box is totally blank, showing no roles at all.

reported here: https://wordpress.org/support/topic/wp-multisite-with-domains/#post-15992128

**Comment by dannyvankooten** [comment]
Is the plugin network of site-activated?
