### ISSUE TITLE
Add a PHP filter to decide if Koko should be loaded

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#170]
in script.js there is a user agent filter, it would be nice if we can overwrite that, either with a JS snippet or with a PHP snippet. 

I guess the easiest way would be to check if some global js variable exists and use that if it's available?

```
    // do not track if user agent looks like a bot
    if ((/bot|crawler|spider|crawling|seo|chrome-lighthouse|preview/i).test(navigator.userAgent)) {
      return
    }
```

https://wordpress.org/support/topic/filtering-out-specific-user-agents/

In addition, a PHP filter that can return true or false for loading Koko could be even better. That way any complex PHP code snippet can be used to decide if koko should be loaded and tracking can be prevented based on any possible PHP condition that way.

**Comment by arnelap** [comment]
the second suggestion, using a PHP filter to check if Koko should be loaded at all would solve this request as well:
https://wordpress.org/support/topic/prevent-referrer-block-list-from-inserting-visitor-views-data/

**Comment by dannyvankooten** [comment]
@arnelap There is a filter called 'koko_analytics_load_tracking_script' which can be used to not load the tracking script.

```php
add_filter( 'koko_analytics_load_tracking_script', '__return_false' );
```

**Comment by arnelap** [comment]
awesome :)
