### ISSUE TITLE
Feature Suggestion: Network Analytics Page for WP Multisite

### ISSUE THREAD

**Issue by beckej13820** [ibericode/koko-analytics#172]
Koko Analytics is doing a great job on my WordPress Multisites keeping analytics for each individual subsite. I wish there was a network analytics page that could give some summary statistics on the entire network of WordPress Sites.

I'd like to be able to:

- See overall traffic on all sites
- Instead of seeing which pages have the most traffic, see which subsites have the most traffic
- Be able to click the links in the report and go directly to a single sites analytics report

**Comment by usu-access** [comment]
Agreed - this would be a huge improvement and super helpful to be able to see analytics across the entire network.

**Comment by gunha** [comment]
Tritto! This would be a fantastic help to multisite managers.

**Comment by dannyvankooten** [comment]
Hello everyone. I'm still listening. Just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.
