### ISSUE TITLE
PHP API to record pageview for post ID and expose stats 

### ISSUE THREAD

**Issue by kennydude** [ibericode/koko-analytics#174]
I was wondering on the planned stability, or even if I should use the function `collect_in_file` in order to track pageviews of content which doesn't output a html page, but has a wordpress post id?

Thanks!

**Comment by dannyvankooten** [comment]
@kennydude I don't want to make that function an official part of Koko's public API but you're probably good to go using it for the foreseeable future. If your page is not outputting HTML then it's pretty much the only option right nowbesides inserting into the relevant databases tables directly.

That said, I'll leave this issue open so we can think of an official function to support this.

**Comment by dannyvankooten** [comment]
For anyone reading: as of version 1.1, the following PHP functions are available for theme or plugin developers to call:

`koko_analytics_get_most_viewed_posts()` to get a list of the most viewed posts.
`koko_analytics_get_realtime_pageview_count('-1 hour')` to get the total number of pageviews in the last hour.
`koko_analytics_track_pageview($post_id)` to track a pageview to the post with ID `$post_id`

Have a look at the documentation inside [src/global-functions.php](https://github.com/ibericode/koko-analytics/blob/master/src/global-functions.php) for more information on how to use these functions.
