### ISSUE TITLE
Suggestion: Default date period: Last 14 Days

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#175]
I’d like to suggest that an option to display statistics for the last 14 days is added under the settings.

I know the last 14 days are shown at the WordPress Home panel, but I would like to have the option to see it as the default under the Analytics tab.

Source: https://wordpress.org/support/topic/default-date-period-last-14-days/

**Comment by dannyvankooten** [comment]
Hmm. With defaults being so highly subjective, should we create a filter hook or setting that sets the value of the `last X days` preset option?

**Comment by dannyvankooten** [comment]
Done in c4ba9a496c1722a4a893cd995310fb42b06914e6
