### ISSUE TITLE
fatal error trying to update

### ISSUE THREAD

**Issue by harttheo** [ibericode/koko-analytics#176]
In trying to update got a fatal error message 

Fatal error: Default value for parameters with a class type hint can only be NULL in /home/regional/public_html/wp/wp-content/plugins/koko-analytics/src/class-rest.php on line 118

I don't know  how to code and don't know what this means.

**Comment by dannyvankooten** [comment]
﻿Hello. It sounds like you are on a very old PHP version that does not understand type declarations in method parameters.Please ensure you are running PHP 7.3 or higher.Op 10 dec. 2022 om 16:31 heeft harttheo ***@***.***> het volgende geschreven:﻿
In trying to update got a fatal error message
Fatal error: Default value for parameters with a class type hint can only be NULL in /home/regional/public_html/wp/wp-content/plugins/koko-analytics/src/class-rest.php on line 118
I don't know  how to code and don't know what this means.
