### ISSUE TITLE
Issue: Start from X views in Koko / Migrating from other analytics solution

### ISSUE THREAD

**Issue by jh4tz** [ibericode/koko-analytics#177]
Hi all, 

I have a client who uses Jetpack and their analytics functions. 
They are a successful eCom business and have 100k website views over 5 years and use that as social proof on social media posts. 
I want to remove Jetpack and install Koko but want to show the previous analytics from previous years. 
Is there a way to modify the database entry for 'all-time' views in Koko? Or a way to start counting from a certain value so that the previous total is maintained?

Any ideas?

Many thanks!
- Johnny

**Comment by dannyvankooten** [comment]
Sorry it took this long for me to respond. Ideally, data would be migrated properly and inserted into the database in the format that Koko Analytics expects. But as that is quite some work, an easier method would be to simply insert the historical number on a given day if all you care about is that the total number of visitor matches over time.

That could be as simple as running the following query:

```sql
INSERT INTO wp_koko_analytics_site_stats (date, visitors, pageviews ) VALUES ( '2023-08-30', 100000, 100000 );
```

That would tell Koko that 100K visitors and 100K pageviews occured on 2023-08-30. This will mess up the comparisons over week/month/year views though, but a simple way to improve upon the above query is to insert a row per year. That way the comparisons will only be off for the first month. 

Hope that helps a bit (or anyone reading this by now).

**Comment by dannyvankooten** [comment]
Closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas).
