### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by esmoyer** [ibericode/koko-analytics#180]
Hi, I am trying to check out your plugin, but am getting the same error as this issue: https://github.com/ibericode/koko-analytics/issues/176

Site is on PHP 7.4+; but can't seem to figure out why it crashes our site. 

Fatal error: Default value for parameters with a class type hint can only be NULL in /home/customer/www/completeptlincoln.com/public_html/home/wp-content/plugins/koko-analytics/src/class-rest.php on line 118

**Comment by esmoyer** [comment]
Got it figured out. Apparently an old plugin re-wrote the htaccess file and appended a line to the end that caused the issue. Thanks for helping point me in the right direction!

**Comment by dannyvankooten** [comment]
Crazy - glad to hear it @esmoyer. I'll remember it in case I come across a similar issue in the future!
