### ISSUE TITLE
Default cookie setting to false/no on multisite

### ISSUE THREAD

**Issue by vilkkkas** [ibericode/koko-analytics#181]
Is there a possibility to somehow define default setting of cookie usage for unique visitors to --> no/false in multisite installation?

**Comment by dannyvankooten** [comment]
```php

add_filter( 'default_option_koko_analytics_settings', function( $options ) {
	$options['use_cookie'] = 0;
	return $options;
});
```

https://developer.wordpress.org/reference/functions/get_option/#hooks
