### ISSUE TITLE
open_basedir restriction warning

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#183]
FastCGI sent in stderr: “PHP message: PHP Warning: require(): open_basedir restriction in effect. File(/www/wp-content/plugins/koko-analytics/src/functions.php) is not within the allowed path(s)…

Can we prevent this warning just so it doesn't clog the log?

https://wordpress.org/support/topic/getting-a-recurring-error/

**Comment by dannyvankooten** [comment]
This is probably the endpoint installer that is trying to install the optimized endpoint repeatedly, then running into this error and then removing it immediately.

I'll see if we can rate limit it to once per day, but a manual approach would be for people to disable the custom endpoint manually:

```php
define( 'KOKO_ANALYTICS_CUSTOM_ENDPOINT', false );
```
