### ISSUE TITLE
Feature: Most viewed post of the day widget

### ISSUE THREAD

**Issue by hchouhan** [ibericode/koko-analytics#188]
Is there a possibility to create a most viewed post/custom post widget/block for a day?

example:
`[koko_analytics_most_viewed_posts number="10" days="today" post_type="news,posts,products" show_count="true"]`

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/display-top-posts-of-the-day/#post-16871775

**Comment by dannyvankooten** [comment]
The real issue here was combining multiple post types into a single list, but it can now be done! :tada: 

```
 [koko_analytics_most_viewed_posts number="10" days="1" post_type="news,posts,products" show_count="true"]
```
