### ISSUE TITLE
Feature suggestion: Option for hourly stat collection

### ISSUE THREAD

**Issue by austinginder** [ibericode/koko-analytics#19]
I think the daily stat collection makes sense as the default option. That goes with the performance focus of the plugin. I would be interested to see an hourly increment option. Even if that includes a warning that it may impact performance.

Also an hourly option would allow me to potentially import historically stats from another open source stats tracking system. 😉 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Hey @austinginder,

Just thinking out loud here: for how long would you like to retain hourly stats? A few weeks? A year? Longer? 

I was thinking to build-in some kind of consolidation feature that combines multiple rows of a smaller time-unit into a larger block, to help aid performance and to decrease storage requirements. 

That would allow us to, for example, retain hourly stats for a couple of week before they are consolidated into daily stats. And then the daily stats are in turn consolidated into monthly stats after a year or two. Thoughts?

**Comment by austinginder** [comment]
Well if I'm honest, I'd want to maintain full history with all of it's details. Even if that means it has to be exported and deleted from the website in order to keep the backend running smoothly. 

Having full stats history is comparable to uploading full resolution photos to Google Photos. I mean sure Google Photos can automatically downsize the originals thus saving a ton of space however... it's my data and therefore I want to keep it at full quality for the chance that I'd want to go back and use something at the full size.

**Comment by dannyvankooten** [comment]
Oh yes, it would absolutely be an option, not something that is done automatically. Was just thinking out loud for how to make hourly storage scalable even for larger-traffic websites.

**Comment by askel45** [comment]
> Hey @austinginder,
> 
> Just thinking out loud here: for how long would you like to retain hourly stats? A few weeks? A year? Longer?
> 
> I was thinking to build-in some kind of consolidation feature that combines multiple rows of a smaller time-unit into a larger block, to help aid performance and to decrease storage requirements.
> 
> That would allow us to, for example, retain hourly stats for a couple of week before they are consolidated into daily stats. And then the daily stats are in turn consolidated into monthly stats after a year or two. Thoughts?

I like this one!

**Comment by dannyvankooten** [comment]
Moved to #216
