### ISSUE TITLE
Weekdays and month names should not be hardcoded, WordPress or PHP localization should be used

### ISSUE THREAD

**Issue by MagicFab** [ibericode/koko-analytics#194]
I noticed new string for translation available that are normally handled by PHP [1], or even by WordPress functions [2]

It's particularly important to avoid this as translation tools don't provide much context and capitalization is different depending on locale. When looking at the reports this will undermine credibility among readers noticing such small mistakes.

An example is found in assets/src/js/util/dates.js for the monthsFull and monthsShort array.

[1] https://brainbell.com/php/localizing-dates.html
[2] https://developer.wordpress.org/reference/classes/wp_locale/ , https://claudiorimann.com/localized-date-formats-in-wordpress/

**Comment by dannyvankooten** [comment]
Agreed! The goal was to be able to use the date format as set in WordPress' settings, but it added quite a bit of complexity. 

I'm currently leaning towards using the date formatting from the browser as that will be both easiest and most performant. This does however mean that it could not match the language of the dashboard itself, if the browser language differs from the WordPress admin language. 

Another option would be to use the date JavaScript library that WordPress ships with, but it comes at quite a heavy cost of 600 kB... Which is 12 times the size of the script for our dashboard itself. Would really love to be able to use a simple format and be done with it. Thoughts?
