### ISSUE TITLE
User role exclusion UI enhancement

### ISSUE THREAD

**Issue by sdegetaus** [ibericode/koko-analytics#2]
Hello! I stumbled upon your plugin and immediately was hooked! Just yesterday I was researching for Google Analytics alternatives, but hadn't thought about a built-in solution! I have been meaning to contribute to open-source projects, so here it goes!

In my opinion, the current system to exclude pageviews by user role is clunky. For example, once a single user is selected, there is no way to unselect it.

In the screenshot I have attached, I propose a different system. I am not going to explain it, as I think it is a pretty common and intuitive system, understood by the majority.

![proto_settings_00](https://user-images.githubusercontent.com/30123984/68424743-3e345680-016a-11ea-8d42-a3d56cd0dc45.jpg)

What do you guys think? 🙂

**Comment by dannyvankooten** [comment]
Love it @sdegetaus! Threw the current setting in real quickly just to get it out there (and working), but your suggestion looks way more intuitive to me.

We'll get to it!

**Comment by dannyvankooten** [comment]
Closing this as after some thought, I think the current implementation is "good enough". If it sucks enough, I think it is up to the browser to come up with a better implementation.
