### ISSUE TITLE
Feature suggestion: Being able to purge analytics data or have data purged older than a certain date range

### ISSUE THREAD

**Issue by lukecav** [ibericode/koko-analytics#20]
Add setting to be able to purge data older than a date range or being able to set data to only be stored for XX number of days.

**Comment by dannyvankooten** [comment]
Hey @lukecav,

Chances are, this is actually already in the (development version of the) plugin. It'll be included in the next plugin update!

e02ddfa21744976d50414498f4f09ae6fd0ab704

![Screenshot of purging](https://github.com/dannyvankooten/koko-analytics/raw/master/assets/src/img/screenshot-2.png?v=1)
