### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by rghedin** [ibericode/koko-analytics#237]
Hi,

I noticed that Koko Analytics demands three mouse clicks to change pre-sets of date range. Maybe too many? 😄

Since left and right arrows are already present in Koko, I was wondering if it would be possible to add other shortcuts for pre-sets, at least to cycle date views (day only, weekly, monthly, and year). Maybe `d`, `w`, `m`, and `y`?

**Comment by dannyvankooten** [comment]
Hello @rghedin,

Thank you for the suggestion! I've created a feature suggestion for it here so that people can vote on it: #239
