### ISSUE TITLE
Difference between demo and plugin install

### ISSUE THREAD

**Issue by iamzoltan** [ibericode/koko-analytics#240]
Hello!

Thanks for this project and making it open. I would love to contribute.

I just installed the plugin via wordpress, and it appears that the analytics available showcased in your demo are different than the ones I have available. Is this a dev version? How can I set up my plugin to mirror what you are gathering on the demo?

thanks for your help!

**Comment by dannyvankooten** [comment]
Hello @iamzoltan,

The [demo](https://www.kokoanalytics.com/?koko-analytics-dashboard) uses the Koko Analytics Pro add-on, but we have put that on hold for the time being as I am transitioning into full-time employment later this week. I am not ready to continue that while being unsure of how much time and energy I'll have to support it in my free time.

I might merge those features into the free plugin at some points in the future though. It has an event-tracking feature which allows you to track all sorts of custom events, which is what you see with the "article feedback"  or "screen resolution" components. 

Hope that clarifies. 

Best,
Danny

**Comment by iamzoltan** [comment]
Hi @dannyvankooten ,

thanks for your reply! I hope you do merge those features in the future.

 How can I get involved? I would be interested in adding features, i.e a map for example.
 
 Cheers,
 Zoltan
