### ISSUE TITLE
Add exactly total visitors and pageviews as tooltips on mouse hover

### ISSUE THREAD

**Issue by rghedin** [ibericode/koko-analytics#241]
In the main ribbon of page stats, Koko shows total visitors and pageviews as rounded numbers, which is fine, but falls short when exactly data is needed.

This can be fixed easily adding the exactly numbers as tooltips on mouse hover, using `title="X"`, like this:

```html
<span title="89.825">89.6K</span>
```

Resulting in:

<img width="225" alt="Captura de Tela 2024-03-01 às 06 44 25" src="https://github.com/ibericode/koko-analytics/assets/19216581/1c26a118-b16e-4b9b-8e23-96810dc7501f">

**Comment by dannyvankooten** [comment]
I like it @rghedin: small and simple change, yet very effective! Would be open for a PR if you're up for it. 

Otherwise I'll get to it when I can.

**Comment by rghedin** [comment]
I can't code, @dannyvankooten ☹️

Take your time, there's no rush for this 😊
