### ISSUE TITLE
Bug in documentation?

### ISSUE THREAD

**Issue by edent** [ibericode/koko-analytics#249]
On both https://www.kokoanalytics.com/kb/show-number-of-pageviews-for-a-given-page/ and https://www.kokoanalytics.com/kb/show-number-of-pageviews-for-a-given-page/ it says:

> As of Koko Analytics version 1.3.7, you can use the **342** shortcode to show the number of visitors or pageviews for a given post on your site.

I assume `<strong><span class="koko-analytics-counter">342</span> </strong>` is being injected by an unfiltered `[koko_analytics_counter]`?

**Comment by dannyvankooten** [comment]
Hah, you're absolutely right! Fixed. Thanks for the heads up!
