### ISSUE TITLE
Highlight weekends in charts

### ISSUE THREAD

**Issue by rghedin** [ibericode/koko-analytics#256]
A simple change in colors to improve readability of long range charts. I made a mock-up:

![weekends-highlight-1](https://github.com/user-attachments/assets/90be924d-86d8-451d-909b-93cc46b007b2)

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by spigotdesign** [comment]
I was just looking for a css or data hook for this the other day. Great idea!
