### ISSUE TITLE
Feature Request: post view count in posts menu

### ISSUE THREAD

**Issue by jan-vandenberg** [ibericode/koko-analytics#258]
I am migrating away from JetPack to Koko, but I also still use Post Views Counter plugin (by dFactory) for one reason only: it shows the counts per post in de post menu (and it is sortable):

![image](https://github.com/user-attachments/assets/60b04919-10cb-4df6-bfc6-aa0308f7b754)

Would this be possible in future versions of Koko?

**Comment by jan-vandenberg** [comment]
At the moment it is just the total. Jetpack does something similar by the way: it shows a link (a graph icon) that takes you the specific (time-range) stats for that post.

**Comment by dannyvankooten** [comment]
Thank you @jan-vandenberg. Can you please add your upvote to the feature request that discusses this idea? See #204. 

I'm using those feature requests to help prioritise what to work on next.

**Comment by dannyvankooten** [comment]
Closed in favor of [show statistics in Posts overview table in WP Admin #204](https://github.com/ibericode/koko-analytics/discussions/204).

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by dannyvankooten** [comment]
![image](https://github.com/user-attachments/assets/ba083dbc-0881-4608-a5e8-c70360312453)

![image](https://github.com/user-attachments/assets/6fec94ad-482f-482f-9b2a-ceeb96d823e1)

This has been added to [Koko Analytics Pro](https://www.kokoanalytics.com/pricing/).
