### ISSUE TITLE
Format numbers for improved readability

### ISSUE THREAD

**Issue by ocean90** [ibericode/koko-analytics#264]
There are a few places where `fmt_large_number()` isn't used and/or the number is below 10k. Examples:

| Totals | Pages | Widget |
|--------|--------|--------|
| <img width="400" alt="" src="https://github.com/user-attachments/assets/d42616ee-b377-4f33-8f4f-cc6eb4fe5499"> | <img width="400" alt="" src="https://github.com/user-attachments/assets/12a4dc7a-280c-4e09-b751-0f0ab7da1837"> | <img width="400" alt="" src="https://github.com/user-attachments/assets/7fd8c48a-218e-4bdd-bb86-0afd150e57d4"> | 

In above views it would be great if we could format the numbers with a thousand separator, for example by using `number_format_i18n()`:

<img width="400" alt="Bildschirmfoto 2024-11-14 um 08 18 54" src="https://github.com/user-attachments/assets/9ce9c606-ed13-4c0c-9548-6ceed887c4c3">

<sup>(In Germany groups of thousands are separated by `.` )</sup>

What do you think?

**Comment by dannyvankooten** [comment]
@ocean90 I agree! Actually did just this a few days ago (70e08c6b22aa8a53434afbaabb04e802a00d3e9b), so not much to be done here except for me to release it. Love it when that happens. :smile: 

Closed in 70e08c6b22aa8a53434afbaabb04e802a00d3e9b

**Comment by ocean90** [comment]
@dannyvankooten Thanks for the quick response! Didn't notice the commit until now. 🙈 

Looking at `fmt_large_number()` and it still does return the raw number if the number is below 10000. I think in https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/functions.php#L303 we should also use `number_format_i18n()`.

Or is there a reason why you are not using `number_format_i18n()`? Same for https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/functions.php#L312-L316


And for the totals and the dashboard widget I don't see any changes:
* https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/views/dashboard-page.php#L103
* https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/views/dashboard-page.php#L123
* https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/views/dashboard-widget.php#L22
* https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/views/dashboard-widget.php#L44
* https://github.com/ibericode/koko-analytics/blob/8e9ffbf7a7243456eb53b43c55093e65a54160a3/src/views/dashboard-widget.php#L58

**Comment by ocean90** [comment]
Thank you!
