### ISSUE TITLE
Unexpected errors logged about migrating data after fresh install of version 1.4.5

### ISSUE THREAD

**Issue by JosKlever** [ibericode/koko-analytics#269]
Hi Danny,

Yesterday I freshly installed version 1.4.5 on a site and found some errors in the log afterwards. It looks like some migration functions were executed without reason. Everything seems to be working fine, but it might need some checks/tweaks to prevent the errors. I've redacted the client info, but you find the errors in the attachment.
[koko-1.4.5-error-log-after-new-install.txt](https://github.com/user-attachments/files/17775803/koko-1.4.5-error-log-after-new-install.txt)

Thanks,
Jos

**Comment by dannyvankooten** [comment]
Thanks @JosKlever - I'll look into it! 

The migration process is a little weirdly named as it's also used for setting up the database in its initial state. In this case it looks like one of the earlier migration steps somehow failed and that is messing up a later step, but I'll look into it in more detail some time next week!

**Comment by dannyvankooten** [comment]
Hi @JosKlever,

Looking at the errors a bit more closely; it looks like there was a race condition where the migrations were executed twice, the latter process starting while the former was still running. 

This is an issue that I'll need to prevent from happening (or at least decrease the chances of it). 

For this site unless you're absolutely certain everything works, I recommend uninstalling the plugin (to wipe the database) and then re-activating it once again to run the migrations once more while hoping the race condition doesn't trigger this time. 

Great catch by the way, thx for bringing it to my attention!
