### ISSUE TITLE
Oudated scripts.js caused 400 errors with tracker

### ISSUE THREAD

**Issue by austinginder** [ibericode/koko-analytics#30]
Noticed the tracker was causing 400 errors via Chrome devtools [as shown here](https://drive.google.com/file/d/1U1cmSDTsAQhAUiBTga2WwSZqr3no1fXV/view?usp=sharing). This was due to my CDN serving up an old copy of the scripts.js file. I was able to manually correct by purging my CDN. I'm wondering if cache busting could be built into the plugin itself. One method would be to rename scripts.js to a dated version and updated if it includes breaking changes.

**Comment by dannyvankooten** [comment]
Hi @austinginder,

> One method would be to rename scripts.js to a dated version and updated if it includes breaking changes.

What's weird is that this should already be built into the plugin using a fairly standard WordPress method of adding the plugin version to the URL to the script file. So whenever the plugin is updated, caches are busted.

https://github.com/ibericode/koko-analytics/blob/master/src/class-script-loader.php#L34

Are you running a plugin that strips off this version number by any chance?

**Comment by austinginder** [comment]
Ah yes, that was it. I forgot I have Perfmatters installed with this option enabled: https://perfmatters.io/docs/remove-query-strings-from-static-resources/.
