### ISSUE TITLE
Large numbers are cut-off from chart y-axes

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#31]
<img width="160" alt="image" src="https://user-images.githubusercontent.com/885856/70782576-9bce4b00-1d87-11ea-867e-f7af1883b78a.png">

**Comment by flowdee** [comment]
Experiencing this too after the latest plugin update.

<img width="474" alt="Bildschirmfoto_2019-12-15_um_09_30_27" src="https://user-images.githubusercontent.com/2278756/70860111-a9b5d480-1f1d-11ea-8e04-9fa1df03cacb.png">
