### ISSUE TITLE
Feature suggestion: record Google search terms

### ISSUE THREAD

**Issue by weebsnore** [ibericode/koko-analytics#32]
Hey,

Love this extension - great work!

One feature I'd like is to see what search engine phrases people are using to find my site.

Is this possible?

Cheers!

**Comment by dannyvankooten** [comment]
Hey @weebsnore,

Unfortunately this isn't really possible anymore anno 2019, as Google is no longer sharing this information. 😞 If someone reading this knows a way, please do let me know.

**Comment by callaloo** [comment]
Using the GainWP plugin, I sometimes see google analytics shows some of these stats. I bet the best option for this is to just use the Google Search console.

**Comment by Chaiavi** [comment]
This is a biggy

I know that some other analytics plugins allow connecting to Google search console and recieve that information from there

Matomo charges big bucks for this feature
Plausible enables it for free

**Comment by bhadaway** [comment]
3 years later...

Perhaps the Google Search Console API is now able to handle integration more easily than when this issue was first closed?

https://developers.google.com/webmaster-tools/
