### ISSUE TITLE
Feature suggestion: Track time on page

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#33]
This is one of those features that while cool, I never really use it or use it for decision making. So I am fine leaving this out personally. 

Please do let me know in the comments below if you feel otherwise though, I might be overlooking something.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by rghedin** [comment]
It's important to analyse if people are actually reading your blog or simply arriving and leaving. Average short time spent on a page may sinalize something is wrong with it; on the other hand, longer periods mean people are enjoying/appreciating what you're doing. For blogs that sell ads directly, it shows brands that even small audiences can engaje heavily, a strength of/for small projects (like mine).

It isn't the most important metric to have, but it's a nice, useful one.

**Comment by LeBaux** [comment]
50:50, it can realistically help you identify content that is not engaging.

**Comment by callaloo** [comment]
I vote for it, especially for the reason given by @rghedin .

**Comment by 12nick12** [comment]
Can we please get this I would love it.

**Comment by dannyvankooten** [comment]
Moved to #215
