### ISSUE TITLE
Chart: use multiple bar chart instead of stacked bar chart

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#34]

**Comment by Pavlo-Pavlo** [comment]
I like this idea.
For an example I can offer statistics https://www.liveinternet.ru/stat/mk/. It is very popular in the Russian-language segment, including due to its simple and clear graphics.
https://prnt.sc/qm8htf

**Comment by dannyvankooten** [comment]
@Pavlo-Pavlo Would you prefer a line chart over a bar chart?

**Comment by Pavlo-Pavlo** [comment]
Hello!

I like this option more - https://prnt.sc/qqmbar.

Respectfully yours, Pavel

**Comment by Pavlo-Pavlo** [comment]
Line chart
