### ISSUE TITLE
Feature: Add setting to specify default view (this week, this month, etc.)

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#35]
As requested here: https://wordpress.org/support/topic/today-view-and-default-view/

Alternatively, do not use a setting but switch to the last known view instead? So if you navigate away after looking at the "this month" view and then return through the menu link on the left, the "this month" view is re-opened.

**Comment by Pavlo-Pavlo** [comment]
Right idea
By default, I use statistics for one day

**Comment by danielrunvegan** [comment]
Hey @dannyvankooten, is there a reason you ditched the "default to last selected view" again? Right now the chart always defaults to the current month view, so I need at least 2 more clicks to get to my preferred view. I'd love to have the option to set the main chart to always show the last 28 days, ending with the current day (similar to the dashboard widget, which always shows the last 14 days).
