### ISSUE TITLE
Feature suggestion: option to redirect Dashboard to Analytics

### ISSUE THREAD

**Issue by askosh** [ibericode/koko-analytics#38]
For a lot of us the WordPress Dashboard serves little to no use, it would be super cool to have an option to redirect the Dashboard to the Analytics page instead. 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Hello @askosh,

I'm not sure whether this is something to make it into the plugin itself, but as a code snippet this is how I would do this:

```php
add_action('admin_init', function() {
    global $pagenow;

    if ($pagenow === 'index.php' && ! isset($_GET['page'])) {
        wp_safe_redirect(admin_url('index.php?page=koko-analytics'));
        exit;
    }
});
```
