### ISSUE TITLE
Feature suggestion: show realtime visitor count

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#44]
Technically this is a little hard to build into the current set-up, but there are options. Visitors is problably impossible without hurting performance and/or the privacy centric approach, but _pageviews in last X minutes_ should be doable.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by renehesse** [comment]
i would love this function! with this function you should be able to see on which pages the most traffic is coming in.

**Comment by dannyvankooten** [comment]
![image](https://user-images.githubusercontent.com/885856/72972972-a6d7ba80-3dcc-11ea-9105-960fdd8894ad.png)

**Comment by renehesse** [comment]
that would also be an interesting number for the dashboard widget

<img width="595" alt="Screen-2020-01-23 10-45-07" src="https://user-images.githubusercontent.com/13309968/72973409-7e03f500-3dcd-11ea-8c41-79911559bab3.png">

**Comment by dannyvankooten** [comment]
@renehesse I think I'll leave it out on the dashboard widget just to keep things simple, because the data showing there grows stale really quickly. Personally I don't look at the dashboard page all that much after I'm logged in.

**Comment by renehesse** [comment]
no problem. i have the dashboard in my field of view about 10 hours a day, that's why the idea 😄

**Comment by dannyvankooten** [comment]
![image](https://github.com/ibericode/koko-analytics/assets/885856/f393de5e-d54c-4c9f-b971-e03a4af46c0c)

3 years later, but how about something like this for the dashboard widget?

**Comment by renehesse** [comment]
This looks great. To make it comparable with Google Analytics, a time window of 30 minutes may be suitable, which I have now established as the standard.

<img width="332" alt="Bildschirmfoto 2023-10-26 um 10 35 16" src="https://github.com/ibericode/koko-analytics/assets/13309968/8f7eba45-173d-4f47-a132-9f40e661d2fc">
