### ISSUE TITLE
Feature suggestion: track visitors to archive pages

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#45]
Like category and tag pages. Currently these are ignored, to save some processing and because usually they are not as important as the homepage and singular post-type pages.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by LeBaux** [comment]
For SEO purposes it is interesting. TSF, for example, does not index archive pages from page 2 by default because these are low-quality pages.

I would keep it as an option.

**Comment by danielrunvegan** [comment]
Whether category pages are interesting depends on if/how you use them. For instance, on our blog they are an integral part of the user experience and are directly linked via the main menu. So for us, it is very interesting to know how many people click through to the different category pages (or get sent there via Google), as it gives us an idea about which general topics appeal most to our visitors.

**Comment by danielrunvegan** [comment]
I thought some more about this. Posts, pages and archive pages all serve different purposes on a wordpress site, so maybe it's not the best idea to lump them all together in one big pageview ranking.

How about adding a toggle on the top of the table to allow for switching between: posts - pages - archives - ALL (maybe even 404s, as suggested in another thread?)

I think this would greatly enhance the usability of the data. For instance, you could switch to the pages ranking to see which of your landing/product pages are doing best at one glance, instead of combing through a long list of mainly posts in order to spot the pages.

The toggle solution may also work for the referrer view: show top domains only - show individual urls

**Comment by rghedin** [comment]
Uhh, I didn't know they were ignored. My blog isn't built around these archive pages, but there are a lot of links to tags and categories that a new visitor or someone interested may find useful, therefore spend some time digging them.

For me, it's worth the hit on performance. Archives, although not as popular as home and posts' pages, are important in any blog.

**Comment by LeBaux** [comment]
> Whether category pages are interesting depends on if/how you use them. 

That is why I said from SEO perspective. I absolutely agree with your case and point.

**Comment by danielrunvegan** [comment]
> > Whether category pages are interesting depends on if/how you use them.
> 
> That is why I said from SEO perspective. I absolutely agree with your case and point.

I actually was referring to dannyvankootens statement about the importance of archive pages, not yours - so we're definitely on the same side here :-)

**Comment by MulderFrank** [comment]
Yes please.
If I'm correct it currently does count the pageviews of the Category, Tag, Author and Homepages, but it doesn't report them in the list of visited pages. (they're all set to `"post_id":0`)

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/add-tracking-to-custom-header/

**Comment by roam92** [comment]
Koko is great! But if only individual posts and pages are counted, then it's not only leaving out Archive pages like Category, Tag, and Author – but also the website's actual home (Index) page, if that's not a singular post/page?

**Comment by msaari** [comment]
I'd love to see term archives in the stats among the posts. I have sites where the term archives are some of the most popular content, and it would be great for Koko to be able to handle them.

**Comment by dannyvankooten** [comment]
We're moving feature suggestions to GitHub discussions. Continuation of this idea has moved here: #212
