### ISSUE TITLE
Blank screen bug

### ISSUE THREAD

**Issue by lukecarbis** [ibericode/koko-analytics#48]
### Description

When visiting a date range containing only two days, Koko shows a completely blank screen (due to a javascript error).

```
[Error] RangeError: Invalid time value — admin.js:1:29852
```

### How to reproduce

Select two dates next to each other, and refresh the page.

(Alternatively, just visit https://yoursite.com/wp-admin/index.php?page=koko-analytics#/?start_date=2020-1-28&end_date=2020-1-29)

Another form of this bug occurs if, when making a date selection, the user chooses only a single date, then refreshes the page before selecting the second date.

![2020-01-27 09-44-54 2020-01-27 09_46_14](https://user-images.githubusercontent.com/1097667/73143778-e0b90180-40e9-11ea-9226-5fe836e8f964.gif)

### Temporary fix

Since the date range is stored in Local Storage, refreshing the page doesn't help. Nor does manually specifying different dates. The user needs to empty their browser's Local Storage.

**Comment by dannyvankooten** [comment]
Hey @lukecarbis,

Awesome, thank you so much for finding this. This is in Safari, from the looks of it, correct?

**Comment by lukecarbis** [comment]
@dannyvankooten yes, that’s right.
