### ISSUE TITLE
Total visitor count not displayed correctly above 100K

### ISSUE THREAD

**Issue by danielrunvegan** [ibericode/koko-analytics#49]
The total visitor count shows only two (instead of three) numbers before the "K" when the count exceeds 100.000. See the screenshot below, where it should read "17xK".

I tested this in Chrome, Firefox and Opera with the same result.

![kokoanalytics](https://user-images.githubusercontent.com/60192889/73442949-09453380-4356-11ea-9c5d-f67946632c97.jpg)

**Comment by dannyvankooten** [comment]
Good catch @danielrunvegan! Thank you for reporting. Looked over this far too many times in my development dashboard, haha.

**Comment by danielrunvegan** [comment]
Glad I can help :-) Funnily enough, after a reboot the count shows correctly right now. I haven't figured out the pattern yet.

By the way, I love the latest version update!
