### ISSUE TITLE
Feature suggestion: Track outbound link clicks

### ISSUE THREAD

**Issue by bluebit27** [ibericode/koko-analytics#55]
It would be helpful to track how the visitor left the website. Track any outbound links that were clicked for the day, week, month, year.

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Thank you for the suggestion @bluebit27!

Most likely, or at least initially, this will be supported by custom event tracking (#10) so that it's not limited to link clicks but can be used to track any custom event.

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/outbound-click-stats/

**Comment by dannyvankooten** [comment]
This can now be done using [event tracking](https://www.kokoanalytics.com/kb/tracking-events/).
