### ISSUE TITLE
Version 1.0.9 not counting/showing data properly?

### ISSUE THREAD

**Issue by davinian** [ibericode/koko-analytics#58]
Hi, updated to 1.0.9 yesterday and think Page/Referrer Visitor/Pageview count is not working correctly. I am also running Google Analytics and numbers are noticeably different.

I'm using cache but everything prior to v 1.0.9 seemed to be ok.

Any thoughts? Let me know if you need me to check anything.

Regards, David

**Comment by dannyvankooten** [comment]
Hey @davinian,

Can you elaborate on what numbers are off exactly, or do you mean that _all_ numbers are off after the latest update? A screenshot would really help.

**Comment by davinian** [comment]
Hi @dannyvankooten, looks like all numbers seem off - I was also seeing Referrer traffic from a CreateSend campaign and although the pageviews for the affected Page continued to grown the Referrers stop and was no longer being counted.

I see you updated the "referrer blocklist" in the last update, I cannot see createsend in the list, so wondering if something else in the update changed?

Regards, David

**Comment by dannyvankooten** [comment]
Hey @davinian,

Do you have a full URL as an example for the CreateSend referrer you should be seeing so that I can run some tests?

**Comment by davinian** [comment]
@dannyvankooten Hi, I have decided to remove Koko and a number of other plugins from my main site as something was also causing db corruption (not suggesting Koko was responsible).

I am using Koko on other sites and it seems to be ok, so it's likely a unique issue with the way my server is set up.

Kind regards,
David
