### ISSUE TITLE
Ignore requests by known profilers

### ISSUE THREAD

**Issue by valorin** [ibericode/koko-analytics#60]
If you use a tool like https://www.fastorslow.com/ to profile your site, all of it's requests appear to show up in the analytics. For a low-traffic site, this throws off the stats. Would it be possible to automatically identify and ignore these sorts of requests somehow?

**Comment by dannyvankooten** [comment]
That'd be lovely, will have to determine whether there's a generic method of identifying those. For the site mentioned (which uses Lighthouse under the hood) it seems we can check whether the `User-Agent` header contains `Chrome-Lighthouse`.

**Comment by valorin** [comment]
Awesome, thanks! :-)
