### ISSUE TITLE
Feature suggestion: Show pageviews column on post/page overview pages

### ISSUE THREAD

**Issue by svatoupravdu** [ibericode/koko-analytics#61]
I'd love to see **Hits** column in admin post/page list just to have brief overview on how many times the articles have been read. WP Statistics plugin has such feature, just simple numbler would be enough, chart in column is not necessary.

![screenshot-wp-statistics com-2018 12 04-16-14-56](https://user-images.githubusercontent.com/6311102/78468791-485b8080-771b-11ea-84e6-b859183e9f00.png)

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Hmm, interesting. For what time period are those hits though? Should it be configurable from the UI?

Verstuurd vanaf mijn iPhone

**Comment by danielrunvegan** [comment]
I like this idea, too! Maybe we could have an option to choose a default time period in the settings and use it for both the main chart view and this new column in the post/page list?

**Comment by svatoupravdu** [comment]
For me personally I don't need time period setting, total hits since ever is enough, just to keep things silly simple. Thanks!

**Comment by askel45** [comment]
I support this. Even if possible, @dannyvankooten could implement a shortcode to show the views on the frontend per post.

**Comment by svatoupravdu** [comment]
I've been collecting stats for last 6 months and I still miss the column with total hits count most. The column could still be optional though, there's an option pane above posts list in admin which could bear such checkbox.

**Comment by svatoupravdu** [comment]
Never mind, I achieved my goal by installing WP Code Snippets plugin and enabling this snippet for admin area only:

```
add_filter('manage_post_posts_columns', function($columns) {
	return array_merge($columns, ['pageviews' => __('Pageviews', 'textdomain')]);
});
 
add_action('manage_post_posts_custom_column', function($column_key, $post_id) {
	global $wpdb;
	if ($column_key == 'pageviews') {
		echo $wpdb->get_var(
            $wpdb->prepare( "SELECT SUM(pageviews) FROM wp_koko_analytics_post_stats WHERE id = $post_id" )
        );
	}
}, 10, 2);
```

**Comment by larsschafer** [comment]
https://wordpress.org/support/topic/counter-behind-the-postings/#post-14611944

**Comment by dannyvankooten** [comment]
Moved to #204
