### ISSUE TITLE
Feature suggestion: Show homepage and category pages in the table that now only shows posts & pages

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#62]
The table in the bottom-left corner of the analytics page currently only shows posts, pages and other public post types. Should we add the homepage and category (archive) pages to this table?

Requested by:
- https://secure.helpscout.net/conversation/1129506308/22636?folderId=3775430

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
I'd like to be able to do this eventually but it is not easy to do right now, as the plugin references pages and posts by their post ID (for performance, storage and simplicity reasons). So if a page does not have a post ID (eg. archive pages or a non-fixed front page) then it is only counted towards the site total, but not stored to show-up in the table on the bottom-left of the dashboard.

**Comment by matthias-schaefer** [comment]
Maybe you can add a fake id in this case? Something like 99999999 which will never happen in real life (at least, very unrealistically). is_home() is true in this case and the wp option "page_on_front" is 0, so there would be ways to recognize and trigger it

**Comment by giuliopons** [comment]
> I'd like to be able to do this eventually but it is not easy to do right now, as the plugin references pages and posts by their post ID (for performance, storage and simplicity reasons). So if a page does not have a post ID (eg. archive pages or a non-fixed front page) then it is only counted towards the site total, but not stored to show-up in the table on the bottom-left of the dashboard.

You should consider to add those data because categories are important pages for many sites.

A possibile solution:

Create another table to store term data:  `wp_koko_analytics_term_stats` in this table id points to a `term_id` of wordpress term table.
Modify your code to detect if you have to store data in your koko posts table or in the new koko terms table.
Store terms data separately and merge them in a query when you're going to draw charts in wordpress dashboard.

It should not hurt performances too much, since you have to check for terms only if your page id is -1.
In backoffice dashboard you have to make some UNION query to put together data.

Another possible solution is to use just one table and add a `type` field that says "post" or "term", you should also modify your primary key (it should be `date-id-type`) this maybe is easier to fetch data.

**Comment by EgyCodePro** [comment]
> I'd like to be able to do this eventually but it is not easy to do right now, as the plugin references pages and posts by their post ID (for performance, storage and simplicity reasons). So if a page does not have a post ID (eg. archive pages or a non-fixed front page) then it is only counted towards the site total, but not stored to show-up in the table on the bottom-left of the dashboard.

At first, thank you for your nice plugin that work very fast as said! and the most important it's not causing site overload! I'm happy to share my solution to add category and other taxonomy sub categories pages with other users who want to track visits to their categories pages, this will also work for any other taxonomy type categories other than default wordpress taxonomy category type!

Add this code in this file in the plugin directory "/plugins/koko-analytics/src/class-script-loader.php"

`if ( is_category() ) {
			$cat_pot_id = get_term_meta( get_queried_object_id(), 'koko_cat_post_id', true);
			if ( $cat_pot_id != false ) {
				return $cat_pot_id;
			}
		}`

And add this to Wordpress theme functions.php file

`//Create post for current taxonomy page
function ec_create_category_post_data() {
	global $wpdb;
	$queried_object = get_queried_object();
	//Check if we are in category or any taxonomy page like products category page
	//This will work with other custom wordpress plugins that create other taxonomies other than
	//default wordpress categories!
	if ( isset( $queried_object->taxonomy ) && $queried_object->taxonomy != '' && !empty( $queried_object->taxonomy ) && isset( $queried_object->term_id ) ) {
		//Check if the post exists for our current taxonomy page
		$cat_exist = $wpdb->get_row( $wpdb->prepare( "SELECT ID, post_title FROM $wpdb->posts WHERE post_name = %s LIMIT 1", 'cat-slug-' . $queried_object->term_id ), ARRAY_A );
		//Update taxonomy post data in case category or taxonomy name or title has been changed!
		if ( $cat_exist != false && !empty( $cat_exist ) && $cat_exist['post_title'] != $queried_object->name && current_user_can('administrator') == true ) {
			$postdata = array(
				'post_title'     => $queried_object->name,
			);
			//for debugging
			//echo '<pre>' . print_r($cat_exist, true) . '</pre>';
			$where = array( 'ID' => $cat_exist['ID'] );
			if ( false === $wpdb->update( $wpdb->posts, $postdata, $where ) ) {
				error_log( 'Could not update post for taxonomy in the database' );
				return;
			}		
		}
		//Insert post data for current taxonomy page
		if ( $cat_exist == false ) {
			$postdata = array(
				'post_title'     => $queried_object->name,
				'post_status'    => 'publish',
				'post_name'      => 'cat-slug-' . $queried_object->term_id,
				'comment_status' => 'closed',
				'ping_status'    => 'closed',
				'guid'           => $queried_object->term_id,
				'post_type'      => 'koko_cat_page',
			);
			if ( false === $wpdb->insert( $wpdb->posts, $postdata ) ) {
				error_log( 'Could not insert post for taxonomy in the database' );
				return;
			}
			$post_id = (int) $wpdb->insert_id;
			$koko_cat_post_id = $post_id;
			update_term_meta( $queried_object->term_id, 'koko_cat_post_id', $koko_cat_post_id );
		}
	}
}
add_action( 'template_redirect', 'ec_create_category_post_data', 11 );

function alter_koko_cat_page( $permalink, $post, $leavename ) {
	if ( $post->post_type === 'koko_cat_page' ) {
		$post_cat_id = (int) $post->guid;
		//Get the permalink for taxonomy page
		$permalink = get_term_link( $post_cat_id, 'category' );
		return $permalink;
	}
	return $permalink;
}

add_filter( 'post_link', 'alter_koko_cat_page', 99, 3 );`

I hope this help!

**Comment by arnelap** [comment]
https://github.com/ibericode/koko-analytics/issues/126

**Comment by dannyvankooten** [comment]
I'm just closing this issue to keep the GitHub issue list about issues and bugs only. We're still tracking this feature suggestion here: #212
