### ISSUE TITLE
Feature suggestion: select default timeframe for Dashboard Statistics page

### ISSUE THREAD

**Issue by Spartelfant** [ibericode/koko-analytics#63]
Hi,

In my opinion it would be really great if there was an option to select a default timeframe to display on the Dashboard Statistics page (`example.com/wp-admin/index.php?page=koko-analytics/`). Right now it's always displaying the current month, but I'm much more interested in our visitor numbers over the past 28 days, and whether that's going up, or down, or staying the same. And because the selection of a timeframe is done by using absolute dates in the URL, I also can't make a bookmark for the 'past 28 days' timeframe.

Ideally the default timeframe would be something the user could configure, but personally I'd also be happy with just the last 28 days being the plugin's default.

Thank you for your time, thank you for this wonderful plugin, and please let me know if my (admittedly limited) PHP skills can make any contribution towards this request.

Kind regards,
Bart Kuijper

**Comment by Spartelfant** [comment]
Wow that was quick!

Next feature request: how can I give this plugin 6 stars on wp.org?

**Comment by danielrunvegan** [comment]
> Wow that was quick!
> 
> Next feature request: how can I give this plugin 6 stars on wp.org?

I second that request, haha :-)

**Comment by dannyvankooten** [comment]
Haha, well, it was a great feature request so.. Thanks so much for the kind words guys, very much appreciated!
