### ISSUE TITLE
Feature request: output analytics to text file

### ISSUE THREAD

**Issue by dddddddavid** [ibericode/koko-analytics#64]
Hi Danny, 

Thanks for Koko - it's fabulous & I look at it several times a day - just to see the numbers - I like to have a feel of what's going on.

I want to see the numbers without opening a web browser - I already use conky to display a tail of the remote machine's access log on my local desktop, and I'd like to be able to do the same with the stats from koko.

This is currently displayed in my koko dashboard:

Total visitors
204 +3%
5 more than previous period
Total pageviews
504 +87%
235 more than previous period
Realtime pageviews
10
pageviews in the last hour

I'd like to be able to commit that information to a file on the server which updates every X minutes. Then I can schedule SCP to my local machine.

Does that make sense?

**Comment by dannyvankooten** [comment]
Hello @dddddddavid,

It does - and I like the idea but will have to give it a thought on how to make this work and be flexible enough to be useful for as many users as possible. 

An alternative method that I'd like to share is to use the REST API endpoints that come with Koko Analytics. Here's an example to talk to the REST API using a simple bash (shell) script.

1. Install the [Application Passwords](https://wordpress.org/plugins/application-passwords/) plugin.
2. Create a password for your user account so we can use that password to talk to the REST API. [Some instructions can be found here](https://wordpress.org/plugins/application-passwords/) under "Creating Application Password Manually"

You can then talk to [the endpoints that are already built into Koko Analytics](https://github.com/ibericode/koko-analytics/blob/master/src/class-rest.php) like this:

**Get the number of realtime visitors in the last hour**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.COM/wp-json/koko-analytics/v1/realtime?since=-1%20hour 
```

**Get (daily) data for visitors & pageviews to any page on the site between two dates**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.com/wp-json/koko-analytics/v1/stats?start_date=2020-04-01&end_date=2020-04-30
```

**Get top 10 referrers between two dates**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.com/wp-json/koko-analytics/v1/referrers?start_date=2020-04-01&end_date=2020-04-30&offset=0&limit=10
```

**Get top 10 most-viewed pages/posts/... between two dates**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.com/wp-json/koko-analytics/v1/posts?start_date=2020-04-01&end_date=2020-04-30&offset=0&limit=10
```

I hope that gives you some ideas on what is already possible.

**Comment by dddddddavid** [comment]
Thanks Danny. Works a treat :)
![screen](https://user-images.githubusercontent.com/57491766/79789061-8ecaf500-8341-11ea-80b3-f210667b4f13.png)

**Comment by dannyvankooten** [comment]
Whoa, neat. Made me check out conky, looks so good. Can't wait to build something with it as well!

---

One thing to add to my previous comment is that the realtime endpoint only stores information for a maximum of 1 hour, so the `since` URL parameter only works properly on strings that `strtotime` understands like `1 minute`, `5 minutes` with a maximum of `1 hour`.

Example:

**Get number of visitors in last hour**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.COM/wp-json/koko-analytics/v1/realtime?since=-1%20hour 
```


**Get number of visitors in last 10 minutes**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.COM/wp-json/koko-analytics/v1/realtime?since=-10%minutes 
```

**INVALID: Get number of visitors in last 12 hours**
```
curl --user "USERNAME:APPLICATION_PASSWORD" https://WEBSITE.COM/wp-json/koko-analytics/v1/realtime?since=-12%hours 
```

The last one will silently fail at this stage as the endpoint doesn't yet validate the parameter.
