### ISSUE TITLE
Add a filter to prevent trying to symlink custom endpoint in place

### ISSUE THREAD

**Issue by alpipego** [ibericode/koko-analytics#71]
As explained in #70, my setup is not 100% default.

If a user is on the settings page, it tries to symlink the custom endpoint into place. In my setup, the `ABSPATH` will never be writable, so I get a log entry on every pageview `NOTICE: PHP message: PHP Warning:  symlink(): Permission denied in .../plugins/koko-analytics/src/class-admin.php on line 319`.

Could you introduce a filter to prevent the `install_optimized_endpoint` method from being executed?

**Comment by dannyvankooten** [comment]
Hey @alpipego,

I think we should just check whether `KOKO_ANALYTICS_USE_CUSTOM_ENDPOINT` is enabled and if it is: not attempt to install the file, as it would mean the user already copied the file manually. That would also account for your use case, right?
