### ISSUE TITLE
multisite support

### ISSUE THREAD

**Issue by dkegle** [ibericode/koko-analytics#72]
There are some issues using koko analytics for wordpress multisites. The db tables are correctly created, but only the primary site seems to be getting filled with data, not the other sites. Has anyone else had this issue?

**Comment by dannyvankooten** [comment]
Hello @dkegle,

Can you tell us a bit more about your set-up, are you using Multisite with subdomains or with subdirectories?

**Comment by dkegle** [comment]
I am using subdirectories.

**Comment by dannyvankooten** [comment]
And do you have Koko Analytics network-activated on on a per-site basis?

**Comment by dannyvankooten** [comment]
Never mind, I was able to replicate the issue. It'll be fixed in the next plugin update!
