### ISSUE TITLE
Feature Request: Add custom referrers to block list

### ISSUE THREAD

**Issue by askel45** [ibericode/koko-analytics#75]
When using Google analytics, it detects some referrers that I end up adding to its filter list. Is there a similar way this plugin can adapt to this feature so that users can add custom filters in the backend that can then show up in the plugin's referrer blockage list?

**Comment by dannyvankooten** [comment]
Hello @askel45,

Not yet, but I like the idea. 

What would be ideal for you, a  textbox in the settings page where you can enter domains separated by new lines? Something more advanced, e.g. using wildcards?

**Comment by askel45** [comment]
Hi @dannyvankooten . I am not a developer, so you can decide which is the best solution that can accommodate either. I like the textbox one, preferably with the separator being something like `|` so that the spacing can be compact.

**Comment by dannyvankooten** [comment]
Next plugin version will have 2 new filter hooks that allow adding custom domains to the blocklist or running custom logic to determine whether to ignore a URL.

- Example 1: [add custom domains to referrer blocklist](https://github.com/ibericode/koko-analytics/blob/master/code-snippets/add-domains-to-referrer-blocklist.php)
- Example 2: [run custom logic to ignore certain URL patterns](https://github.com/ibericode/koko-analytics/blob/master/code-snippets/ignore-some-referrer-urls.php)

**Comment by askel45** [comment]
Would you also set it in a way that it ignores any referrers in the plugin's list if they are already in the list when someone tries to insert them via the custom area? Or that is not a problem?

**Comment by dannyvankooten** [comment]
@askel45 Not a problem, it is accounted for. The custom domains are an addition to the existing blocklist, so they will not replace it.

**Comment by askel45** [comment]
Thanks. One last question, how to filter out the referrers I add from my previous data?
