### ISSUE TITLE
Question: Making future suggestions modular

### ISSUE THREAD

**Issue by askel45** [ibericode/koko-analytics#76]
Hi. I was thinking out loud if it is possible for some of the future feature requests to be made modular in a way that they only work when activated through settings? I am sure not everyone will want to track everything. Would this work in a real environment? This would really help with performance.

**Comment by dannyvankooten** [comment]
Hi @askel45,

We'll go by this on a case-by-case basis. If something is complex or a performance hit, we'll make it modular. But more importantly: it most likely won't end up in the plugin if it is one of those two things, at least not by default.
