### ISSUE TITLE
Possible Bug: Language in 1.0.14

### ISSUE THREAD

**Issue by danielrunvegan** [ibericode/koko-analytics#77]
After updating to 1.0.14 the plugin shows the english strings, although the page language is set to German.

Edit: "If you enjoy using Koko Analytics ..." is properly translated.

**Comment by dannyvankooten** [comment]
Finally managed to fix this in version 1.0.15. Still not entirely sure why WordPress.org didn't pick up on the new translation files right away...

You may have to force-check for updates in your WordPress admin to see an available update for the translation files btw.
