### ISSUE TITLE
Feature suggestion: Add 'Yesterday' to Default date period

### ISSUE THREAD

**Issue by askel45** [ibericode/koko-analytics#79]
I like showing yesterday's stats by default since I log in to my site every day to check on the stats of the previous day. Is this possible? 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Hey @askel45,

I've added vote buttons to this issue / feature suggestion to gauge interest. 

For now please know that as a workaround you should be able to use "Today" as the default view and then hit the left-arrow button to quickly browse to yesterday.

**Comment by askel45** [comment]
Took me a while to realize what you meant by 'left' arrow.

**Comment by dannyvankooten** [comment]
Ugh, sorry, should have said left-arrow key. 🙈

**Comment by askel45** [comment]
> Ugh, sorry, should have said left-arrow key. 🙈

This! I found it from the analytics page. This is more intuitive. I usually find that when trying to click on a specific date from the calendar that I have to double click for it to show the stats. Is that by design? Because clicking once does nothing.
