### ISSUE TITLE
Feature suggestion: Export to CSV / Import from CSV

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#8]
For example, to make it easier to migrate data for Koko Analytics alone from one website to another website.

Would also help in #7 so data can be stored permanently while also purging it from the production database.

---

Please vote on this feature suggestion using :+1: or :-1: below.

**Comment by Zodiac1978** [comment]
If you develop a new website in parallel and then want to switch to the new site you are always loosing those devloping weeks/months. Export/Import would be a killer feature!

All third-party tracker are just working in this case, but all local plugin solutions then suffer from this gap in the statistics. Exporting and Importing (with a feature to erase all existing data and just keep the imported data) would be a huge help in this case.

**Comment by askel45** [comment]
I support this! Sometimes I do export WordPress posts via Tools>Export to begin afresh and it would help to have a feature where I can quickly import/export the Koko stats as well.

**Comment by larsschafer** [comment]
https://wordpress.org/support/topic/import-data-from-koko/#post-14611650

**Comment by ecollart** [comment]
Hello,
in my case, it's to create graphs to include in a traffic report.

**Comment by dl-sn** [comment]
I would love a function to export the data. Cause I could create easily reports if I had the export file

**Comment by dannyvankooten** [comment]
Moved to #217
