### ISSUE TITLE
easy way to relocate the symbolic link of koko-analytics-collect.php file to the right directory

### ISSUE THREAD

**Issue by imc84** [ibericode/koko-analytics#81]
Recently I installed and delete-reinstall the plugin both of v1.0.13 and v.1.0.15 so many times on my WP website, but it did not work until today before I found the cause of the problem.

Here's a situation that this plugin is not working correctly and no pageview are being recorded. It has two triggers;
When 1) your root of WP installation is located to web server's sub-directory like "/public_html/wp/", not a root directory like "/public_html/", and 2) you are setting the 'Site Address (URL)' value to a different value with the 'WordPress Address (URL)' in the WP 'General Settings' page, (For example, you set the Site Address to "https://blahblah.blah" and set the WordPress Address to "https://blahblah.blah/wp".), now the koko analytics plugin doesn't record anythings.
 
This plugin had created a symbolic link of the "koko-analytics-collect.php" file (the custom endpoint) in the root of WP installation(the /public_html/wp/) when its first running after being installed.

If you set the WordPress Address with sub-directory like "https://blahblah.blah/wp", the symbolic link works well, so this plugin records visitors data. However, if you set the WordPress Address without sub-directory like "https://blahblah.blah", the symbolic link doesn't works, so this plugin doesn't records. It because the symbolic link is created to wrong directory. The link should have been created to the directory that is equivalent the WordPress Address. The directory is web server's root like "/public_html/".

Today I fixed this problem by copying the "koko-analytics-collect.php" file to web server's root directory and editing properly the paths relate with data gathering in the file. I don't know whether this is an unique case by me, or things like real bug or cases out of the maker's purpose.

I think there are still many other WP bloggers are interested in an alternative to google analytics, and some of those are setting the Site Address and WordPress Address differently, and they can try this nice plugin, but give up to use easily if they think it doesn't work well.

As an user, I suggests the koko analytics plugin needs to get an awareness of path to WP Homepage, for it to create the symbolic link to the right directory. Or, I hope this plugin give its users an option to relocate the symbolic link to the directory they want by using web interface only.

If you think there are things have much higher priority than my suggestion, please add this case to the answers to "No pageviews are being recorded." question in the official WordPress plugin webpage's FAQ section. The question is answered "This is usually a file permissions issue. The first thing to check is whether the /wp-content/uploads/pageviews.php file exists and is writable by your web server." There was any clue for this case. Finding this solution was very hard for me.

**Comment by dannyvankooten** [comment]
Hey @imc84,

Thank you for the heads up. This is definitely high priority for me, I'd even say it is a bug. 

I'll look into it, there shouldn't be any need for users to dig into the internals of Koko Analytics just to get it working.
