### ISSUE TITLE
Support Request: Explain how Koko analytics determines unique...

### ISSUE THREAD

**Issue by askel45** [ibericode/koko-analytics#83]
...visitors and pageviews @dannyvankooten. I was having a discussion with your plugin support person on wp.org but I haven't found response in 3 days. Anyways, if I am not wrong,,

1. when a cookie is set, Koko counts a returning visitor as unique (hence the visit is not counted) but the pageview is counted? (And does this explain the discrepancy in the number of visitors and page views per post?).
2. When a returning visitor views the same page, is the view counted? (with GA it seems the same pageview by the same visitor is not counted even if the person reloads the page 15 times!)
3. When it comes to Koko, how do you define a unique visitor and a unique pageview?

**Comment by dannyvankooten** [comment]
Hello @askel45,

From the [plugin FAQ](https://wordpress.org/plugins/koko-analytics/):

**What is the definition of a “pageview”?**

A pageview is defined as a view of a page on your site. If a user clicks reload after reaching the page, this is counted as an additional pageview. If a user navigates to a different page and then returns to the original page, a second pageview is recorded as well.

**What is the definition of a “visitor”?**

A visitor represents the number of sessions during which your website or a specific page was viewed one or more times.

Hope that clarifies!

**Comment by askel45** [comment]
I think this explains why I see all the discrepancies. Could be my visitors clicking internal links and then coming back to the same page, though I don't know why this should be counted again. If only there was a column to compare these repeat views and another that combines them into one!
