### ISSUE TITLE
Custom referrer snippet not working 

### ISSUE THREAD

**Issue by askel45** [ibericode/koko-analytics#86]
Followup  for #75  .1. how to filter out the referrers I add from my previous data? 2. @dannyvankooten I have had the filter on for a week and the URLs I shared above are not being blocked.

**Comment by dannyvankooten** [comment]
Hello @askel45,

Please share the complete and exact snippet you have in place and also where you placed it on your website (in what file). That way I can take a look.

**Comment by askel45** [comment]
This is the code I have...
```
// Add custom referrers to Koko's refferer blocklist
add_filter( 'koko_analytics_referrer_blocklist', function() {
	return array(
		'int.search.myway.com',
		'int.search.tb.ask.com',
	);
});
```
I place my Koko analytics plugin codes in a custom plugin in the plugins directory (for the custom theme and WP purposes).

**Comment by dannyvankooten** [comment]
That snippet looks correct to me, are you sure your custom plugin is loaded and executed correctly?

Also, please note that the snippet will only filter these referrer domains going forward so any previous data will not automagically be deleted.

**Comment by dannyvankooten** [comment]
I just confirmed this to be a bug in the Koko Analytics plugin, it'll be fixed in the next plugin update (without any necessary changes to your snippet already in place).

**Comment by askel45** [comment]
> I just confirmed this to be a bug in the Koko Analytics plugin, it'll be fixed in the next plugin update (without any necessary changes to your snippet already in place).

Okay, thanks. I had to delete the plugin for now since I have been using it only for two weeks. I will reinstall it when this update is made. Have reverted to GA for now.

**Comment by askel45** [comment]
Cool, thanks. I have decided to go back to GA for now. But I will install the plugin afresh when you implement the feature to export data (and to count 404s as well, but this is minor).
