### ISSUE TITLE
Notify user if symlink failed

### ISSUE THREAD

**Issue by timnashcouk** [ibericode/koko-analytics#88]
Follow up-to issue #71 and #70 while looking through exception tracking data, I spotted the symlink warning, I have a near-identical setup to OP in those tickets.

It would be good to flag to the user additional action might (?) be needed, as the plugin does appear to run fine, without the collector in the correct location and modified. 

None of this appears to be documented anywhere other then the above issues as far as I could see.

**Comment by dannyvankooten** [comment]
I wrote down some quick documentation on getting the plugin to successfully switch to the optimized endpoint file here: https://github.com/ibericode/koko-analytics/tree/master/code-snippets

**Comment by dannyvankooten** [comment]
![image](https://user-images.githubusercontent.com/885856/104595694-41cb4380-5673-11eb-8201-d6bfd1f79176.png)

Closed in 9c4ccbf002134e01385cfc79373c0b3207519b50
