### ISSUE TITLE
Feature Realtime stats with links to viewed pages/post/products

### ISSUE THREAD

**Issue by ajgw** [ibericode/koko-analytics#92]
I like the stats of realtime visitors. What this would make outstanding if we can see which content was viewed by visitor.

**Comment by dannyvankooten** [comment]
Hello @ajgw,

Sorry, probably not going to spend any time on this as it moves away from showing aggregated statistics (not specific to any single visitor) to storing visitor-specific information. This goes against Koko's philosophy while also being really hard to make it perform at scale.
