### ISSUE TITLE
Unique page views

### ISSUE THREAD

**Issue by kamauwanjoroge** [ibericode/koko-analytics#94]
I like how Google Analytics does it by combining multiple views of the same page by the same user in the same session into a combined view (or views) no matter how many times they reload the page (or if they click a link in the post and then come back to the same post). This should complement the feature of the unique visits in the plugin alongside the total pageviews.

**Comment by dannyvankooten** [comment]
Hello @askel45,

This is actually what the "visitor" column in the "Pages" table shows you already, unless I'm misunderstanding your suggestion. 

Or do you mean a new section in the "Totals" bar at the top of the dashboard page, showing the combined number of views per visitor but across multiple pages?

**Comment by askel45** [comment]
I think you are misunderstanding my suggestion. This is based on issue #83 was closed before a comprehensive answer was given. If you go to the Behaviour>Overview section of Google Analytics, you see Pageviews and Unique Pageviews. In this section, the pageviews are counted the same way Koko does it (including reloading a page multiple times). But Koko does not have unique pageviews (where multiple visits by one user to the same page in the same session is counted as one unique view) but has unique visits (where a cookie determines a return visitor). What I mean is, you have a similar feature to this that not only counts unique visits, but also unique page views (could be a new column altogether).

**Comment by dannyvankooten** [comment]
Hello @kamauwanjoroge,

I am going to close this as I still don't understand what you are describing (sorry!). It doesn't help that I am not too familiar with Google Analytics. But if you could describe how the count for this new type of metric would work, then I would love to consider it.

Like I understand that Koko currently has unique visitors and total pageviews, but I am not entirely sure how a visitor on a given post differs from a unique pageview. In the bottom-left component on the Koko Analytics dashboard, is the "visitors" column not effectively the same as a "unique pageview"?
