### ISSUE TITLE
Uploads dir error seems like a bug to me.

### ISSUE THREAD

**Issue by akissz** [ibericode/koko-analytics#97]
Maybe this has been discussed in the past. It seems like a bug to me. The default wp unzip does not include a uploads directory. When you activate Koko on fresh wp install, it gives the error about uploads directory not being writable (because its not there.). This is stupid because if you go to the wp media page and upload any media, like a single jpg, this makes the upload directory without error. Why doesn't Koko create the new directory when its not there at first activation. Seems Koko should simply make the directory.

**Comment by dannyvankooten** [comment]
Hello @akissz,

I completely agree, nice catch. Thank you for bringing it to my attention!
